### ISSUE TITLE
New multiword tokens no longer set SpaceAfter=No

### ISSUE THREAD

**Issue by alanakbik** [UniversalDependencies/UD_English-EWT#108]
Hi all, 

the multiword tokens update has "broken" some code in Flair since the marker `SpaceAfter=No` is no longer set for them.  

For example the multiwords `It's` and `you'd` in this dev sentence: 

```
# sent_id = weblog-blogspot.com_marketview_20050210075500_ENG_20050210_075500-0004
# text = It's not quite as freewheeling an environment as you'd imagine: Sergey Brin has actually created a mathematical 'proof' that the company's self-driven research strategy, which gives employees one day a week to do research projects on their own, is a good, respectable idea .
1-2	It's	_	_	_	_	_	_	_	_
1	It	it	PRON	PRP	Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs	8	nsubj	8:nsubj	_
2	's	be	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	8	cop	8:cop	_
3	not	not	PART	RB	_	8	advmod	8:advmod	_
4	quite	quite	ADV	RB	_	5	advmod	5:advmod	_
5	as	as	ADV	RB	_	6	advmod	6:advmod	_
6	freewheeling	freewheeling	ADJ	JJ	Degree=Pos	8	amod	8:amod	_
7	an	a	DET	DT	Definite=Ind|PronType=Art	8	det	8:det	_
8	environment	environment	NOUN	NN	Number=Sing	0	root	0:root	_
9	as	as	SCONJ	IN	_	12	mark	12:mark	_
10-11	you'd	_	_	_	_	_	_	_	_
10	you	you	PRON	PRP	Case=Nom|Person=2|PronType=Prs	12	nsubj	12:nsubj	_
11	'd	would	AUX	MD	VerbForm=Fin	12	aux	12:aux	_
12	imagine	imagine	VERB	VB	VerbForm=Inf	5	advcl	5:advcl:as	SpaceAfter=No
```

Token 1 and 10 should set  `SpaceAfter=No` but don't. Is this an artefact of the update or is it intended?

**Comment by jnivre** [comment]
It is in accordance with the guidelines (https://universaldependencies.org/format.html). See specifically the subsection Untokenized Text and the commented example there. The SpaceAfter comment applies at the token level, not at the word level (when these are distinct).

**Comment by dan-zeman** [comment]
In UD, the term multi-word token usually refers to the annotation like this:

<pre>
1-2	It's	_	_	_	_	_	_	_	_
1	It	it	PRON	PRP	Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs	8	nsubj	8:nsubj	_
2	's	be	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	8	cop	8:cop	_
</pre>

Since there is the interval line starting with "1-2", the following words 1 and 2 are considered as corresponding to the surface form reported at the "1-2" line, but they themselves do not have to be literal parts of the surface string (although they are here). `SpaceAfter=No` is not used with them (it is even forbidden in the guidelines). If there is `SpaceAfter=No`, it must appear on the surface "1-2" line, and it describes the space between the surface token and the following token/word (here, "not").

English contractions like "it's" were not treated as UD multi-word tokens in the previous releases of UD. They were treated as if they were two single-word surface tokens, with no space in between. Such an approach was technically valid but it was against the spirit of tokenization vs. word segmentation, so I think it is a step forward that the annotation now uses MWT.

**Comment by jnivre** [comment]
It would be impossible to apply it consistently at the word level, because the component words of a multiword token do not have to be substrings of their host token.

**Comment by alanakbik** [comment]
@jnivre @dan-zeman thanks for the answers - makes sense! We'll fix it in our corpus loaders.
