### ISSUE TITLE
"not only"

### ISSUE THREAD

**Issue by ethanachi** [UniversalDependencies/UD_English-EWT#114]
Currently, a nontrivial number (22) sentences containing "not only" have `only` labeled as `cc:preconj` and `not` as an adverbial dependent of `only`: [link](http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=5feafa816e526&eud=yes). But this violates UD guidelines (`cc` not expected to have any children). 

Any thoughts on how to resolve this?

**Comment by ethanachi** [comment]
(Same issue with "but also"...)

**Comment by nschneid** [comment]
Looks like GUM has a couple of instances of this annotation, despite passing validation: http://match.grew.fr/?corpus=UD_English-GUM@2.7&custom=5feb51f931072 Do you know why the leaf-cc error is triggered only for EWT?

**Comment by nschneid** [comment]
Here's a query for the bigrams "not only" and "but also": http://match.grew.fr/?corpus=UD_English-GUM@2.7&custom=5feb51f931072

**Comment by amir-zeldes** [comment]
I don't think the validator currently flags this, at least not for the sub-typed `cc:preconj`. It's really a general issue with functional negation though IMO, because for me there is a difference between:

  * You [are not] Kim (it is not the case that you are Kim)
  * You are [not Kim] (you serve as an example of someone who is not-Kim)

I read these differently in terms of intonation as well. But UD guidelines only allow the attachment corresponding to the second (and much less normal) option. I think we all tacitly agreed to live with this issue and benefit from more dependable validation/predictable parser behavior when we accepted that cop, aux and cc don't have children, and I guess I'm OK with it as a caveat of UD. So yes, I think we should probably revise to 'not' attaching to the coordinate head itself, otherwise we're being inconsistent with the rest of UD handling of negating function words.

Also pinging @dan-zeman due to the validation/universal issues involved

**Comment by ethanachi** [comment]
@nschneid I investigated the issue further and am not sure why it's not triggering for your case; there doesn't seem to be an exception in the validator for `cc:preconj`.

That said, I agree with Amir; for consistency with `aux` I agree with making `not` and `also` dependents of the main clauses...

**Comment by ethanachi** [comment]
Patched in e2a3701, thanks for the comments :)

**Comment by amir-zeldes** [comment]
Done in GUM too, amir-zeldes/gum@7b2d9f3
