### ISSUE TITLE
error with 'be like'

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#116]
All instances of "be like" meaning "say" in EWT have "be" as the head and "like" as `compound:prt` (I like this too and we've adopted the same analysis for GUM). There is one error here, which treats the whole thing like a copula predication:

  * Well 6 weeks Later when he came back out He was again working on my mares front Foot and I looked Down and Yeah he had Wholes In his pants In the wrong places I bust out Laughing and **He was like what???**

(answers-20111108091921AAaLK4e_ans-00630)

**Comment by nschneid** [comment]
With [this query](http://universal.grew.fr/?corpus=UD_English-EWT@dev&custom=624d001d4729e) I see a few different analyses in EWT:

1. be -discourse-> like, be -discourse-> (quote)
2. be <-cop- (quote), like <-discourse- (quote)
3. be -compound:prt-> like, be-ccomp-> (quote)
4. (an instance of "He's always like" which makes "always" the root, clearly an error)

I don't think this is `compound:prt`+`ccomp` because the signature of verb particles is that, if the verb is transitive, then the particle can precede or follow the object/complement (and this includes a couple of adjectives, e.g. "cut short"). Quotative "like" always has to precede the quote.

I wonder if a better approach would be:

- be <-cop- (quote), like <-mark- (quote)

Because in stereotypical uses of this idiom, the speaker is enacting the point of view of the quoted speaker, i.e. illustrating how the quoted speaker *was* at the time of speech, as characterized by their speech. So the copula sort of fits in the source of the idiom.

Note that there are also discourse uses of "like" as a filler or hedge, distinct from this idiom. It feels weird to use `discourse` for the internal structure of an idiom.

P.S. This is a great tool for exploring the interaction of deprels and UPOSes: http://universal.grew.fr/meta/UD_English-EWT@dev_table.html

**Comment by nschneid** [comment]
> I think the word order issue is a bit hypothetical, since a heavy ccomp will never come before compound:prt anyway.

Not just heavy phrases:

- He was like "socks" and I was like "shoes".
- *He was "socks" like and I was "shoes" like.

Usually with particle verbs the ccomp alternates with an object NP that allows either order:

- ccomp: Kalkat pointed out that India would be ill-advised to be involved again  
   obj: Kalkat pointed out the issue / pointed the issue out

But:

- *He was like a stupid question.
- **He was a stupid question like.

Also, "like" does not appear to occur as a verb particle beyond this idiom. (Unlike other items which frequently occur as particles: "up", "out", "off", etc.)

So I'm mainly skeptical about the particle designation (if we interpret *particle* as specifically the construction seen in "point out"). Historically, I think the idiom came from copula+PP even if it doesn't feel like a copula now.

What about plain `compound`? I know that is normally for attributive modifiers but as a non-subtyped relation it is also more general than `compound:prt`, I guess.

Or, if you think *particle* in `compound:prt` should be understood in the broader sense of the word, we can go with that. The [current guidelines](https://universaldependencies.org/u/dep/compound-prt.html) aren't very specific.

**Comment by amir-zeldes** [comment]
It's not that I think 'like' is exactly like 'up' or anything, I'm mainly trying to stick it into one of the existing 'bins'. I also don't think plain compound is wrong per se, but it feels weird to have a special constellation just for this item; most post verbal preposition-like things that appear without an argument and create a special sub-sense of the verb are compound:prt, so I'd just as soon lump this with them together (if someone is interested in 'be like' in particular, they can always recognize it by the lemmas)

**Comment by nschneid** [comment]
OK, the post-verb position maybe indicates that `compound:prt` is the least bad solution. Let me edit the guidelines.

**Comment by nschneid** [comment]
How's this: https://universaldependencies.org/en/dep/compound-prt.html

**Comment by amir-zeldes** [comment]
The 'be like' part looks perfect, thanks! But the last example with a movable transitive object + directional RP conflicts with PTB/OntoNotes: although PTB tags directional adverbs as RB for intransitives (sit down/RB, come out/RB), if there is an object and serialization is possible in both orders, it is tagged RP. specifically for the example 'pull it out' we have 2/2 cases: 

  * pull + out/RP

In general a search in ON for "it out" shows out being tagged RP 60 times vs RB 2 times, so I think it's pretty consistent. Looking for all transitive verbs which govern "out" shows 1033 RP : 40 RB (and some might not be phrasal verb constructions of course, e.g. "he meets us out/RB at the car", ch_0018).

I have never loved the whole RP/RB guidelines, but GUM's xpos has followed the above distribution too, to conform with PTB, and the upos is just auto-converted (so RB -> ADV)

**Comment by nschneid** [comment]
You mean the ADV/advmod part? Pretty sure that was a conscious deviation from PTB on the part of the UD. I don't like it because it's the most overt place in the guidelines where semantics is used as a criterion over syntax.

PTB tag guidelines say "the idiomaticity of a particular collocation is not a diagnostic for the distinction" and give a manner adverb insertion test. So I agree with you re: English—but we need to discuss with others before changing it as it is a universal guideline.

**Comment by amir-zeldes** [comment]
> I agree with you re: English—but we need to discuss with others before changing it as it is a universal guideline.

Wasn't that in the English guidelines though? And is `compound:prt` used outside English?

**Comment by nschneid** [comment]
https://universaldependencies.org/u/dep/compound-prt.html is the universal guideline

**Comment by nschneid** [comment]
"be like" is now fixed in EWT. See UniversalDependencies/docs#305 for the `compound:prt` vs. `advmod` discussion.
