### ISSUE TITLE
"at least", "at all", "after all" etc.: preposition tagged as ADV despite attaching as case

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#141]
I assume these were conversion errors:

http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=605fc68a38225

**Comment by AngledLuffa** [comment]
EWT seems to have expressions such as at_RB least_RBS, after_RB all_RB.  PTB has at_IN least_RBS but does agree with after_RB all_RB.

**Comment by amir-zeldes** [comment]
I just ran into this too - so in dev these are now all RB+RBS (I'm not actually sure why in the non-fixed case, since "at" is `case`?) but we also get a bunch of different functions for the non fixed variant's head deprel:

  * http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=607f2f5c0600f&clustering=e.label
  * obl: 18
  * nmod: 66
  * advmod: 4

Personally I like `obl` best (like obl:npmod for JJ extent modifier), but I see the majority is nmod. In these cases I also think the pos tags should be 'normal' (IN + JJS), since the `case` deprel on "at" suggests it's a normal PP.

**Comment by nschneid** [comment]
Regarding the deprel, https://universaldependencies.org/en/dep/fixed.html goes through a bunch of expressions, distinguishing "at least" modifying a quantity/opposite of "at most" (which should be `case` + `nmod:npmod`) from other uses (`fixed` + `advmod`).

The double-`advmod` instances in the corpus look like they should be `fixed`.

"at least once" (currently `obl`) is tricky because "once" is an ADV. Maybe that justifies `obl:npmod` rather than `nmod:npmod`.

"at least on a weekly basis" (currently `obl`) should be `nmod:npmod`, I think, because the head of the PP is "basis".

**Comment by amir-zeldes** [comment]
Interesting... But I think we're just talking about the non-fixed cases - parent of fixed can be advmod, so there is no problem there.

So for the other cases, my understanding of the oblique subtypes (`:npmod`, `:tmod`) was that they are never used when there is a case marker. This is why "at three o'clock" and "in the next year" are not `:tmod`, and why "I ran for three miles" is not `:npmod` - because it's not about temporal or extent semantics, it's just a way of marking that what looks like an unmediated core argument NP is actually oblique. So we'd use the sub-labels for things like "I waited three hours" (not obj), "she arrived today" (not advmod, since upos!=NOUN) etc.

If this is right, I think there shouldn't be `case` + `nmod:npmod`. If this is not right, I'd like some explanation about why "weighing in at 100 lbs" and "arrive in the morning" are not subtyped (I think these would be just `obl` right now)?

**Comment by nschneid** [comment]
Judging by UniversalDependencies/docs/issues/478, `nmod:npmod` appears to be used for certain case-marked modifiers of quantities. I have never fully understood why.

**Comment by amir-zeldes** [comment]
I suspect some of these things are conversion artifacts from SD still (tmod, npadvmod), but I'd like some confirmation (or a rebuttal) about the view I presented above: that these labels exist in current English UD to mark oblique NPs that do not have an explicit case marker. That's how I've understood them, so that's how I've taught them to students and how they are (hopefully) used in GUM as well (and incidentally in UD Coptic). If this is not right, then that's something important to clear up. 

I don't think we have a good way of auto changing all temporal, extent and other PPs to the appropriate subtype based on semantics, and I think that at least the way I understand it is implementable on current corpora (just check there is no case)

**Comment by amir-zeldes** [comment]
I'd like to make a decision on these - my preference would be to keep the fixed/non fixed distinction, since it is meaningful, and do:

  * Fixed cases: advmod, fixed
  * Non-fixed cases: case, obl/nmod (like "at all")
  * Both: xpos=IN, NN (like EWT "in particular", but unlike EWT "at best", which has RB RBS, except one case of IN JJS)

If "least" is the head for the non fixed ones, then I think case+obl makes more sense than tmod or advmod, since we have an actual prepositional phrase analysis. But if that's so, I would expect xpos to be IN+JJS (the adverbial interpretation comes from it being a PP, not from an actual adverb).

If everybody loves "RB" on "in" I guess I can live with it, but the deprels should really be case + obl IMO.

**Comment by nschneid** [comment]
> Judging by [UniversalDependencies/docs/issues/478](https://github.com/UniversalDependencies/docs/issues/478), `nmod:npmod` appears to be used for certain case-marked modifiers of quantities. I have never fully understood why.

I take that back: those examples have case marking on the nmod:npmod *head*.

There are [5 occurrences](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=60863918090d0) with case-marked dependents of nmod:tmod, 4 of them in the same document. They look like errors.

If the rule is that dependents of these relations cannot be case-marked it would be good to mention [here](https://universaldependencies.org/en/dep/nmod-npmod.html) and [here](https://universaldependencies.org/en/dep/nmod-tmod.html) that plain `nmod` or `nmod:poss` should be used instead.

**Comment by nschneid** [comment]
Regarding "at least" etc., as long as we're not going against any of the documented decisions I think it's fine to go with more intuitive tags and deprels.

**Comment by amir-zeldes** [comment]
OK, I've done a fairly extensive analysis of two adjacent and connected RB.* pairs in EWT, here's what I found that I think should be changed:

RB1 --fixed-> RB2:
  * let alone RB RB (VB RB +same fixed in GUM, which has same dominant POS as in PTB, with some variation)
  * of course RB RB (IN NN +same fixed deprels in GUM, same in PTB)
  * at least RB RBS (IN JJS +same fixed in GUM, same in PTB)

RB2 --case-> RB1:
  * at least/most RB RBS (IN JJS in GUM, same case analysis deprels, same POS in PTB)
  * at all RB RB (IN DT in GUM and PTB)
  * after all (IN DT in GUM and PTB)
  * in between (fixed IN IN in GUM, same pos in PTB)

I can make sure these are consistent in GUM but don't want to change EWT given the storm of edits and PRs :)  Are you OK with applying these changes?

**Comment by AngledLuffa** [comment]
- Are you saying the tags should be changed to what you have in ()?
- Also, who is "you"?  I have a bad feeling about this...

**Comment by amir-zeldes** [comment]
Sorry, I meant @nschneid since he posted last :)

But yes, I meant to make them have the tags in brackets, which is consistent with both GUM and PTB. And this should be pretty easy to do, you can use the following [depedit](http://corpling.uis.georgetown.edu/depedit) script:

Contents of `fix_rb_rb.ini`:
```
# RB1 --fixed-> RB2
lemma=/let/;lemma=/alone/	#1.#2;#1>#2	#1:xpos=VB;#2:xpos=RB
lemma=/of/;lemma=/course/	#1.#2;#1>#2	#1:xpos=IN;#2:xpos=NN
lemma=/at/;lemma=/least/	#1.#2;#1>#2	#1:xpos=IN;#2:xpos=JJS
lemma=/in/;lemma=/between/	#1.#2;#2>#1	#1:xpos=IN;#2:xpos=IN

# RB1 <-case-- RB2
lemma=/at/;lemma=/least/	#1.#2;#2>#1	#1:xpos=IN;#2:xpos=JJS
lemma=/(at|after)/;lemma=/all/	#1.#2;#2>#1	#1:xpos=IN;#2:xpos=DT
```

`> python depedit.py --config fix_rb_rb.ini en_ewt-ud-dev.conllu > en_ewt-ud-dev_fixed.conllu`

or on the source docs:

`> python depedit.py --config fix_rb_rb.ini *.conllu`

See the documentation for more file path behavior options. I'd do it myself but I worry there are too many concurrent editors on the files ATM!

**Comment by nschneid** [comment]
Let's wait for #160 to be merged first

**Comment by nschneid** [comment]
@amir-zeldes Outstanding merges are done, so if you could run this quickly it would be faster than it would take me.

I have dealt with a handful of fixes and will turn to the name ADJ problem to see if I can get something sensible done before the data freeze.

**Comment by amir-zeldes** [comment]
Sure, if dev is now up to date I can pull and apply these changes. You just want the source documents in not-to-release updated, right? The main split files will be generated at the end from those?

**Comment by nschneid** [comment]
Yeah if you update the main files I can update the sources.

**Comment by nschneid** [comment]
I figure that's easiest for you, but I have scripts to go in either direction.

**Comment by nschneid** [comment]
"at least 10 - 12 hours a day": I see this uses `fixed` but it shouldn't, right? Modified in the above commit.

"Up to 40 rockets"—corrected this to use `fixed`. 

(Interesting example: "some of the items can have **up to a 60 day delivery**". Note that "up to" precedes the determiner. Not sure it's right to have "up to" modifying "60", but I'll leave it for now.)

"Astrology & Palmistry and everything **in between** including Gemology": this is in/ADP/case between/ADV/nmod—that's incorrect right?

According to https://universaldependencies.org/en/dep/fixed.html, *(at) most/least/best/worst* should attach as `nmod:npmod`. But I think we are going with plain `nmod` in the data. Should the docs be updated?

**Comment by amir-zeldes** [comment]
Yes, I think we should restrict the subtypes to things that don't have prepositions.

**Comment by nschneid** [comment]
Seems straightforward enough to me. @manning @mcdm @sebschu, holler if you think omitting `:npmod` will break something.

**Comment by nschneid** [comment]
> "Astrology & Palmistry and everything **in between** including Gemology": this is in/ADP/case between/ADV/nmod—that's incorrect right?

@amir-zeldes What about this?

**Comment by amir-zeldes** [comment]
I think ADP ADP,  advmod fixed (like "everything there")

**Comment by nschneid** [comment]
I find it kind of ironic that the validator disallows plain ADP/advmod but allows it if it has a fixed ADP dependent. The vagaries of multiword expressions in UD. :)

Anyway I think I'm done with this issue. Glad we've cleaned up these cases!
