### ISSUE TITLE
Missing Person and Number for verbs

### ISSUE THREAD

**Issue by lapalme** [UniversalDependencies/UD_English-EWT#172]
I have recently started to work with UD (in French and English) and in the course of this work, I realised that in the English corpora, there are quite a lot of verbs for which the features Number and Person are not indicated. From what I have seen, this problem is much less acute in French.

Almost the only cases where the Number and Person are specified is when the XPOS is VBZ. Later , I saw this "small print" that might explain this situation
             https://universaldependencies.org/en/morphology.html 

Just to get a sense of the pervasiveness of the "problem", I computed a few statistics on the 25 149 tokens of
      en_ewt-ud-dev.conllu (Version 2.8)

1 930 tokens have Mood=Ind (they are all VERB or AUX)
1 132 tokens have Mood=Ind but no Person and no Number

I wrote a Python script to traverse the tree of each UD and when it encounters a token with an UPOS that is a VERB or AUX and Mood=Ind, it searches for tokens linked by some kind of "subj" deprel. If the subject token has Number/Person, then propagate it to the verb. This allowed to propagate Person and Number to 1 067 tokens which of course have to be checked, but when I looked at them, the great majority seemed right.

So they are still 65 cases left and, given the fact that English is not my mother tongue, I would need some help to decide. What should we do, for some frequent cases:
15 sentences start with "Thank you" : what Person and Number should "thank" have, if any?
many sentences start with verb: such as 
         "Hope this helps",
	 "Do the job...", (should it be Mood=Imp?)
	 "Like sushi, don't like the pad thai" 
	 "Walked in and was outta there in 10 mins ..."
     "Really enjoyed it"

What should the person and number of a modal, such as in "What would you have done differently than him?"
What should the features associated with "would", "have" and "done"?
for the moment: the 62 occurrences of "would" have only "Verbform=Fin" which seems reductionist !!

Is this work useful or worth the trouble ?

thanks for any suggestions

Guy Lapalme

**Comment by amir-zeldes** [comment]
Hi Guy - thanks for raising this! I see this is indeed a problem in EWT, though it's less so in UD_English-GUM, which basically does what your script does as well. [All 11048 verbs labeled Mood=Ind also have a Person feature](https://corpling.uis.georgetown.edu/annis/#_q=TW9vZD0iSW5kIiBfPV8gUGVyc29u&_c=R1VN&cl=5&cr=5&s=0&l=10), so if you need such data feel free to look [here](https://github.com/UniversalDependencies/UD_English-GUM).

As for the cases you raised above:
  * I think "Thank" and "Hope" should be 1st person, though I just discovered they are mistagged as 3 in GUM, will fix.
  * "Do" sounds like an imperative (these also have Person=2 in GUM)
  * For the past tense cases, I think it's really hard to identify them conclusively using a script when they don't have a subject, since it's possible to narrate a 3rd person event with "walked" etc., so I think manual annotation might be the only option
  * For modals, at present neither corpus has Person features, but perhaps we should introduce them based on the same subject-dependent rules. @nschneid , any thoughts on this?
  * For the participles and infinitives connected to the auxiliaries, I think they should not have Person, since that information belongs to the finite part of the construction

**Comment by lapalme** [comment]
Amir

thanks for your reply which shows not only that assigning Person and Number to verbs is useful, but also that it also has been done  for the GUM corpus. So I will try to apply my script to EWT and other English corpora even though it will imply a lot a manual checking after its execution.

Thanks for your other suggestions for the "corner cases'" that I will take into account if others agree with your opinion which seems quite reasonable, at least for a non native English speaker.

Guy

**Comment by nschneid** [comment]
> * For modals, at present neither corpus has Person features, but perhaps we should introduce them based on the same subject-dependent rules. @nschneid , any thoughts on this?

I suppose this raises the question: if a verb or class of verbs (modals) do not exhibit person agreement, do they deserve a Person feature?

The most conservative option would be to only annotate Person if the verb form contrasts with another with respect to person specifically. Thus, neither modals nor past tense forms of verbs other than 'be' would include the feature.

The most liberal option would be to annotate Person on all finite verbs, including modal auxes—which never exhibit agreement and only marginally can be said to have tense—as well as auxes that do exhibit agreement, like 'have' and 'do'.

I'm not sure what there is to be gained by annotating a feature on a verb for which it is wholly irrelevant. At that point it becomes more of a semantic feature than morphosyntactic, right? But maybe it is best to be consistent on a per-verb basis—so exclude modal auxes, but include other finite auxes/main verbs even in the past tense.

> * For the participles and infinitives connected to the auxiliaries, I think they should not have Person, since that information belongs to the finite part of the construction

Yeah, since in a verb cluster only the first is normally finite, I would not expect a Person feature on subsequent ones. So in "What would you have done differently than him?" the feature would be on "would" (if it is specified at all).

If an application wanted to associate the information with the main verb for semantic reasons it would be trivial to propagate it up the `aux` dependency.

**Comment by lapalme** [comment]
Thanks for the precision, but I still have another somewhat related question?

What is the convention when an annotation is "ambiguous"?  Again in the sentence "What would you have done differently than him?", I think that "you" could either be Sing or Plur if we are not given more context.  
Should it be annotated with some kind of default (probably Sing), not at all to leave it unspecified or indicated as both ?

**Comment by nschneid** [comment]
If it's really unspecified then I'd omit the feature, I guess? Looks like "you" in EWT never has a Number feature.

**Comment by amir-zeldes** [comment]
I think it seems reasonable that if finite verbs without over marking get Person, then modals should as well. From a comparative perspective, the cognate German modals are marked for Person, but of course in that language they are still overtly marked. I suppose in English we might still encounter and archaic "thou mayst" :)

In GUM we do tag "you" with Number, which defaults to Sing. We actually have addressee information in comments though, so we can sometimes know it's plural:

```CoNLL-U
# sent_id = GUM_conversation_retirement-88
# addressee = Angela,Doris
# s_type = frag
# speaker = Sam
# text = A good stand of it, if you want any.
...
6	,	,	PUNCT	,	_	9	punct	9:punct	_
7	if	if	SCONJ	IN	_	9	mark	9:mark	Discourse=purpose:145->144
8	you	you	PRON	PRP	Case=Nom|Number=Plur|Person=2|PronType=Prs	9	nsubj	9:nsubj	Entity=(person-11)
9	want	want	VERB	VBP	Mood=Ind|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin	3	advcl	3:advcl:if	_
10	any	any	PRON	DT	_	9	obj	9:obj	Bridge=plant-62<plant-64|Entity=(plant-64)|SpaceAfter=No
11	.	.	PUNCT	.	_	3	punct	3:punct	_
```

These are the rules that produce this behavior currently:

https://github.com/amir-zeldes/gum/blob/dev/_build/utils/ud_morph.ini#L77-L85

**Comment by jowagner** [comment]
> What is the convention when an annotation is "ambiguous"?

Not sure what UD says, but in general you should check the context to find out what was meant. I understand given the history of UD treebanks this can be difficult and somewhat unethical, such as working with the full Enron corpus for the English Web Treebank. Sometimes it is possible to ask the author what they wanted to say. Annotating sentences in isolation is risky as you may not even notice that there is an ambiguity and believe your interpretation is the right one while the author had something different in mind. Of course, after checking all you can, there may still be unresolved ambiguities and the question remains how to annotate them.

> In GUM we do tag "you" with Number, which defaults to Sing. 

From a machine learning perspective, it will be better to leave the feature value unspecified or to apply a special `unknown` value than to assign a default guess such as `Number=Sing` for `you`. Defaults will cause a prediction bias towards the default value. Most importantly, the issue and the action taken should be documented. Ideally, there should be an indicator with the `unknown` values which values must agree and what values are possible. Users of the treebank can then transform these values as needed, e.g. for machine learning it may be good to randomly pick a valid values, subject to agreement constraints, in each training batch.

**Comment by amir-zeldes** [comment]
I won't speak for EWT, but at least for GUM I wouldn't say it's unknown - we pretty much know everything we need to about these texts, and as I wrote above, we have speaker and addressee annotations to distinguish singular and plural addressees. The 'underspecified' cases are more a matter of policy: for example, in text book data (one of the genres in GUM), do we consider the addressee (=reader of the textbook) to be singular or plural? And this is where a somewhat arbitrary convention is introduced (in this case, defaulting to singular), which I think is no different than a lot of other conventions we have. 

ML models will of course be biased towards majority classes, but leaving most "you"s unspecified will just bias them to predict that instead - i.e. no "Number" annotation should be outputted at all, if that is the most common case. I think in this case it's OK to tag things as correctly as we can, and if there are consistent cues for minority classes (e.g. "you all" predicts `Number=Plur`), then I trust that the models are robust enough to figure that out -- mistakes will always happen here and there, but that's probably inevitable, and even humans make them of course.

**Comment by nschneid** [comment]
Merged all the changes. Thanks @lapalme, that was a huge contribution!
