### ISSUE TITLE
NOUN -> NUM 

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#175]
- "dozen" (singular) should be tagged as NUM, as it is analogous to "hundred" etc.
  * "hundreds", however, is tagged as a plural NOUN
- fractional numbers ("half", "two thirds", etc.) should be treated as such. See [`NumType=Frac`](https://universaldependencies.org/u/feat/NumType.html)

**Comment by amir-zeldes** [comment]
Thanks for pointing out `Frac`, will add to next GUM release

**Comment by nschneid** [comment]
Should fractional numbers be tagged as `NOUN` or `NUM`?

[NUM guidelines](https://universaldependencies.org/u/pos/NUM.html):

> A numeral is a word, __functioning most typically as a determiner, adjective or pronoun__, that expresses a number and a relation to the number, such as quantity, sequence, frequency or __fraction__.

So it fits semantically. I am not sure how strongly to weigh the fact that English fractions are most typically expressed in a partitive construction ("1/3 of the pie") rather than as a determiner or adjective.

`NOUN` could make sense because there is a clear singular/plural alternation (a third, two thirds). However, there are currently no NOUNs with a `NumType` feature, and the [NumType guidelines](https://universaldependencies.org/u/feat/NumType.html) omit NOUN from the list of possible tags.

**Comment by nschneid** [comment]
Notes on how I am dealing with ordinals/fractions:

### half, third, fourth, ...
* half the population: DET, fraction - predeterminer use
* a third, two thirds: NOUN, fraction
* the third (book): ADJ, ordinal
* the third (of January), January 3rd: NOUN, non-ordinal, temporarily marking with `Comment=Date`

### second
* a second '1/60th of a minute', 30 seconds: treating as NOUN, not ordinal. Temporarily marking with `Comment=Temporal`
* the second (of January), January 2nd: NOUN, non-ordinal, `Comment=Date`
* the second (book): ADJ, ordinal
* Second, consider...: ADV, ordinal
* the second highest grossing film: ADV, ordinal
* it came second: ADV, ordinal

Questions:

1. Is it a good idea to tag fractions as NOUN rather than NUM? They can be pluralized and seem to systematically require a determiner (except "half" as a predeterminer).
2. Do people agree that dates should be listed as non-ordinal nouns? Would it be better to mark them as ordinal nouns to disambiguate from the measurement sense of "second"? Only the latter can be pluralized.
3. Should empty nodes be added in the Enhanced representation to deal with ellipsis: Did you read the first book(i) or the second ___(i)?
   - Note that dates can occur without the month being specified anywhere in the sentence.

**Comment by amir-zeldes** [comment]
I'm fine with "a third" etc. being a noun synchronically, but I'm a little uneasy with the dates - isn't January 2nd etc. literally an ordinal indication of it being the "how-many-eth" day of the month? I would have liked to see Ord on it. Regarding the POS I would have done ADJ if I hadn't checked, but I see that OntoNotes consistently has these as NN, so I guess NOUN is canon either way.

I don't think we need empty nodes for substitutive ordinals, since there is no orphaned relation here - it can be represented using the usual promotion mechanisms which will treat the adjective as the nominalized head replacing the noun.

And BTW just for fun, you can get pluralization on dates too, it's just unusual - for example:
  * _Meanwhile, on still another November third, I had been in Boston for a conference on the theory that would tolerate putting **all three November thirds** together_ ("November: Lincoln's Elegy at Gettysburg"/Kent Gramm)

**Comment by amir-zeldes** [comment]
Yes, LGTM! 

Obligatory plug: both 3 and 3rd should be the head IMO.

**Comment by nschneid** [comment]
Done with these changes—see updated [English NumType guidelines](https://universaldependencies.org/en/feat/NumType.html)
