### ISSUE TITLE
Tagging differences for "is"

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#189]
"Is" usually gets tagged as AUX, but some fraction of the time it is tagged as VERB instead.  Examples which are common between GUM and EWT are "there is_VERB" and "is_VERB there", which occur quite often in both treebanks.  Another frequent example is "is that", but here the tagging is different.  GUM uses is_AUX and EWT uses is_VERB.  Can we unify these?

@amir-zeldes

**Comment by nschneid** [comment]
> The class AUX also include copulas (in the narrow sense of pure linking words for nonverbal predication).

We had a long discussion about whether "be" in an existential construction counts as a copula: UniversalDependencies/docs#706. It is not obvious whether it should be considered a copula (hence AUX) or a main verb (hence VERB).

**Comment by AngledLuffa** [comment]
I don't have anything to add from a linguistic perspective, but it would be
nice to have a unified treatment in the two largest EN treebanks, whatever
we decide.  I'll even offer to do some or all of the retagging as needed.

**Comment by amir-zeldes** [comment]
I'm not 100% sure what construction we're talking about regarding "is that", but generally my view (and the upos converter's behavior) is that any "be" which is deprel `cop` should be AUX. In existentials, the 'be' is the local root, so it is VERB (and also not `cop` but `root` or `advcl` or whatever clausal function).

I see there is a difference in how EWT handles nested subjects in cases like:

  * The answer is that it 's good

In this case, GUM would have two `nsubj` nodes coming out of good: the predicate clause subject, and subject of the matrix clause. EWT has the first "is" as `root`, and presumably that's why it's not AUX. I assume the motivation for the EWT analysis, which I've run into in some other UD contexts, is telling apart which subject is the matrix subject. 

However you can generally tell which is which in English based on linear order, and I don't think this is reason enough to suddenly treat a copula as the root -- this is IMO very clearly a copula, and we don't really have other cases where recursion alters our analysis of a fundamental construction like copula predication.

So for existentials I think the answer is clear (should always be VERB), and while I think the nested predicate cases should be AUX, the real issue is the tree and the POS tag is just a by-product.

**Comment by nschneid** [comment]
> I see there is a difference in how EWT handles nested subjects in cases like:
> 
>   * The answer is that it 's good
> 
> In this case, GUM would have two `nsubj` nodes coming out of good: the predicate clause subject, and subject of the matrix clause. EWT has the first "is" as `root`, and presumably that's why it's not AUX. I assume the motivation for the EWT analysis, which I've run into in some other UD contexts, is telling apart which subject is the matrix subject.

Yes, this is documented under the policies for copulas at https://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses (and I suspect this is unlikely to change). Given this, it might actually be good to tag as AUX to reflect that it is a copula that has been promoted to head of the clause.

**Comment by amir-zeldes** [comment]
Yes, I am aware of this policy, but it has never been applied to GUM. I feel it is very deeply wrong, for reasons I'm happy to defend. If we are really worried about which subject is which, I think a feature, edep, or pretty much anything else would be better than making a totally normal copula exceptionally become an object-taking root node.

**Comment by nschneid** [comment]
I think this is obsolete due to the outer subjects policy adopted in 2022 (#310)
