### ISSUE TITLE
few, little, many, most: tags & deprels

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#198]
- Several instances of "many", "few", "little" tagged as NOUN, should be ADJ
- Several instances of "few", "many", "most" + "of" where the relation is `obl`; typically it is `nmod`

**Comment by nschneid** [comment]
Related: #170

**Comment by nschneid** [comment]
Deprel errors (should be `nmod`):

- [EWT matches](http://match.grew.fr/?corpus=UD_English-EWT@2.8&custom=611077739b776&clustering=N.lemma&eud=yes)
- [GUM matches](http://match.grew.fr/?corpus=UD_English-GUM@2.8&custom=611077dde6f50&clustering=N.lemma&eud=yes)

**Comment by nschneid** [comment]
(fixed in EWT, leaving open for GUM)

**Comment by nschneid** [comment]
The validator doesn't complain about nmod.

Also worth noting is that these are borderline between adjectives and determiners (#170). The construction in "many of them" is more like "some of them" than "wary of danger". So nmod feels better than obl to me.

**Comment by amir-zeldes** [comment]
I don't doubt it's different from "wary of danger", but for me that's mainly because "danger" is an argument of "wary". The question for me is, is it different from "good for Kim"? Would that be obl for you, even if it's not predicative (say, as an extraposed `amod`, "you should choose a course **better for Kim**, and not the one you'd prefer yourself")? If so, why not "many of X", when we formally say that many is ADJ?

I could go either way honestly, because both nmod and obl basically mean "PP modifier", and these heads are a closed list and rather frequent, so it's easy to enforce and parsers will learn it. I'm just not sure what UD ideology says here, so I'd be curious to see what @dan-zeman thinks.

**Comment by aryamanarora** [comment]
CGEL (p. 539) admits *many/few/much/little* (and their comparative and superlative forms) as determinatives by virtue of:

* He made **so** many mistakes.
* *He made **so** numerous mistakes.

They also satisfy the partitive construction test, e.g. *many of them*.

**Comment by amir-zeldes** [comment]
Yes, these are definitely interesting facts; ultimately the problem is that there are more constructions than we can realistically have tags, so when things don't line up, you have to make some somewhat arbitrary decisions and keep item X in group A and item Y in group B. For example, "several" is like "many" in the partitive:

  * several of them
  * many of them

But it cannot combine with "so":

  * so many of them
  * *so several of them

Some such restrictions seem more semantic than syntactic, but any way you look at it, if we want a closed and reasonably small set of tags, we have to lump things together which are not 100% the same (not just function words, think of count/mass nouns, genus names, and other more fine-grained noun 'subtypes')

**Comment by nschneid** [comment]
Revisiting this—whether partitive modifiers of "many" (and similar determiner-like ADJs) should be `nmod` or `obl`. Both EWT and GUM are inconsistent (including all PP modifiers here):

- [EWT results](https://universal.grew.fr/?custom=6560df286a7fa)
- [GUM results](https://universal.grew.fr/?custom=6560df431c672)

It seems strange to me to say that the partitive construction would be sometimes nmod and other times obl ("some/DET of the books/nmod" but "many/ADJ of the books/obl"). In both cases, shouldn't the quantifier be regarded as promoted to the head of the nominal, thus nmod?

**Comment by dan-zeman** [comment]
> quantifier be regarded as promoted to the head of the nominal

What would be the full nominal before ellipsis and promotion? _Many books of the books_? Sounds odd.

**Comment by nschneid** [comment]
The repetition sounds excessive, but note that the noun could be specified on the head noun of the partitive instead of the dependent: "Many books of the 15 you suggested were unavailable".

I don't think we're necessarily in a position to provide a full account of partitive constructions in UD, but my point is that they seem like a within-nominal modification rather than modification licensed by a normal adjective (along the lines of "afraid of the dark").

**Comment by arademaker** [comment]
I hope this is not a thread hijacking:

> They are the only people who live here.

How to annotate the `only`? To be honest, I am more interested on the formal semantics analysis and not only the syntax annotation, but maybe the syntatic point-of-view can give hints to the semantics. I feel like the `only` is not a modifier of `people` only. Is it a mix of adjective and quantifier?

**Comment by nschneid** [comment]
> Is it a mix of adjective and quantifier?

Semantically yes it is interesting, but in UD we treat "only" like any other adjective amod.

**Comment by amir-zeldes** [comment]
> In both cases, shouldn't the quantifier be regarded as promoted to the head of the nominal, thus nmod?

I used to feel the same, but the word from others (esp. Dan, Joakim I think) was to adhere strictly to using obl when the modified item as ADJ/ADJ, regardless of just about anything else. So in my mind now, UD does not make the distinction of NP internal/predication modification when the head is ADJ/ADV, meaning we have to pick obl here. If we wanted to change this, I feel like there were a bunch of other cases that we consistently ruled in favor of obl using this argumentation, so it would not be as simple as changing just 'many' & the others in this thread, but I don't remember exactly off the top of my head...

**Comment by nschneid** [comment]
EWT predominantly uses nmod for these partitives, so I'd like to get @manning @mcdm etc.'s perspectives before going in another direction.

**Comment by nschneid** [comment]
TBC, I don't have a problem with obl being the default type for dependents of an ADJ functioning in a normal ADJ way (as heading an adjective phrase functioning as attributive modifier or clause predicate). Here though we are talking about an ADJ being coerced into the head of an NP. I thought the whole point of the nmod vs. obl contrast was to distinguish the modifier-in-nominal function since we don't have phrase types.

If we were to adopt a policy that ADJ-headed partitives had to be obl, I think we'd have to start saying that "the least loyal you can find" involves an _adverbial_ relative clause (because the head of the nominal is strictly speaking an ADJ).

**Comment by amir-zeldes** [comment]
I don't disagree with the argument, in fact I think I was on the side of a similar argument in the past, but I recall losing that discussion, so I've come to terms with using obl somewhat robotically when the head is ADJ/ADV. Happy to discuss more if others are open to it.

**Comment by nschneid** [comment]
Today the group decided that `nmod` makes sense for partitives because "many" can be understood as taking the place of the nominal head.

**Comment by rueter** [comment]
> I agree that *of* is licensed by *many*. Actually I think it would make more sense to call *many* a DET. This is a construction that refers to a certain quantity of specific items, not to a property, so it is strange to think of it as an adjective phrase.
> 
> Compare: some/DET of the passengers, 3/NUM of the passengers, a number/NOUN of the passengers. All of these are "nouny" POSes. But: *numerous/ADJ of the passengers.

Hi, this is just for reference, but I would have automatically considered _many_ as a DET or a PRON. This would align with _few_. The pronoun _many_ occurs as NP head without ellipsis with the meaning 'many people'. In addition, _many_ is indeed a quantifier, and since it is not a cardinal numeral, it must be a DET. Are there other languages like English where these are called ADJ in UD?

**Comment by nschneid** [comment]
Yeah, we had the argument awhile ago in UniversalDependencies/docs#786. CGEL classify words like "few" and "many" as determinatives, with partitives being one of the key criteria. And indeed, the universal [DET guidelines](https://universaldependencies.org/u/pos/DET.html) strongly suggest they would be included. But categorizing ones that can be modified by *very* as adjectives is the established precedent in traditional grammars and in English treebanks; there hasn't been enough of an appetite to diverge from this in UD.
