### ISSUE TITLE
Inconsistency in "What a ..." construction

### ISSUE THREAD

**Issue by Oneplus** [UniversalDependencies/UD_English-EWT#24]
```
# sent_id = email-enronsent10_01-0094
# text = What a hoss.
1	What	what	DET	WDT	PronType=Int	3	det	_	_
2	a	a	DET	DT	Definite=Ind|PronType=Art	3	det	_	_
3	hoss	hoss	NOUN	NN	Number=Sing	0	root	_	SpaceAfter=No
4	.	.	PUNCT	.	_	3	punct	_	_
```

```
# sent_id = reviews-377347-0007
# text = What a history.
1	What	what	DET	WDT	PronType=Int	3	det:predet	_	_
2	a	a	DET	DT	Definite=Ind|PronType=Art	3	det	_	_
3	history	history	NOUN	NN	Number=Sing	0	root	_	SpaceAfter=No
4	.	.	PUNCT	.	_	3	punct	_	_
```
and

```
# sent_id = reviews-211797-0012
# text = What a waste of TIME.
1	What	what	PRON	WP	PronType=Int	3	nsubj	_	_
2	a	a	DET	DT	Definite=Ind|PronType=Art	3	det	_	_
3	waste	waste	NOUN	NN	Number=Sing	0	root	_	_
4	of	of	ADP	IN	_	5	case	_	_
5	TIME	time	NOUN	NN	Number=Sing	3	nmod	_	SpaceAfter=No
6	.	.	PUNCT	.	_	3	punct	_	_
```

Since the words `What` are labeled with different dependency relations. Which one is correct?

**Comment by amir-zeldes** [comment]
I think the second one is the most accurate. The third option seems wrong, because it treats this as a predication: what == a waste of time. But I think the structure is the WH equivalent of "such a waste of time", which in Stanford basic dependencies would have been predet, det, and "waste" as the root. 

If we agree this is the same as "such a waste of time", then it can also be embedded into a copular predication, showing that the original structure should not have `nsubj`:

It was such a waste of time
nsubj(waste,It)
cop(waste,was)
det:predet(waste,such)
det(waste,a)

Which is why I think the second analysis is the correct one.

**Comment by manning** [comment]
I suspect the second analysis is best to, though these exclamatives are unlike other nominals since they can't appear in regular nominal positions, such as as dobj. Relevant paper: http://www.tandfonline.com/doi/pdf/10.1080/00437956.2005.11432550 (but not open access). I guess we should read it.

**Comment by manning** [comment]
Other papers on exclamatives:
http://ricknouwen.org/rwfn/wp-content/uploads/2012/01/AC-paper.pdf
http://semanticsarchive.net/Archive/zUyMTY2Z/rett%20exclamatives%20LP%202011.pdf

**Comment by nschneid** [comment]
Mentioned in #281. Standardized to `det:predet`.
