### ISSUE TITLE
the expression `in order to`

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/UD_English-EWT#241]
According to https://dictionary.cambridge.org/us/grammar/british-grammar/in-order-to this can be taken as a "subordinating conjunction". The 16 occurrences in this corpus split the expression into `in order` + `to`, both as `mark` to the following infinitive form of a verb.

**Comment by amir-zeldes** [comment]
I think the split makes sense, since you can drop "in order" and it retains the meaning. So we could say they are both purpose markers, one is mandatory in this construction, and the other is optional:

  * We took umbrellas to stay dry
  * We took umbrellas in order to stay dry

This also makes it clearer that we are dealing with the regular English to-infinitive.
