### ISSUE TITLE
Review a few cases of "very"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#248]
Here are [EWT instances of "very" not attaching to an ADJ/ADV with advmod](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61212ce56d8f2&clustering=X.upos).

Some look like errors. 

For "the very NOUN" (e.g. *the very beginning*) the policy is ADJ/amod.

_Originally posted by @nschneid in https://github.com/UniversalDependencies/UD_English-EWT/issues/205#issuecomment-903145314_

**Comment by nschneid** [comment]
The following 4 tokens have "very" as `advmod` of a VERB (which also has another modifier):
* very neat looking
* very reasonably priced
* very well maintained
* very well adorned

What is the best option here?

1) Keep as is
2) Treat as a degree-modified compound adjective
3) Reattach "very" to the preverbal modifier: _[very well] maintained_ instead of _very [well maintained]_

@amir-zeldes thoughts?

**Comment by amir-zeldes** [comment]
I don't think they're all alike, since some are compounds and some are syntagms based on our deprels. For compounds I would prefer to compound first:

  * very (neat looking) - so very attaches to looking
  * (very reasonably) priced
  * (very well) maintained
  * (very well) adorned

Semantically it's subtle/meaningless(?), but I feel like this way we can say the criterion is clear because it's based on deprel (`compound` mod doesn't get intensification, `advmod` does).

**Comment by nschneid** [comment]
Fine with me (I doubt the `compound` relation is a true reflection of *lexical* compounding so speakers may be processing the attachment differently but I like having a clear policy).

**Comment by amir-zeldes** [comment]
Agreed - also it's probably varied across speakers (a compound that is lexicalized for one speaker might not be for another), so having a formal guideline might be the best you can do, at least in the interest of consistency.
