### ISSUE TITLE
Where the untokenized raw text came from

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/UD_English-EWT#252]
The ChangeLog file says that the untokenized raw content was added in 2016. Does anyone know HOW that was done? The https://catalog.ldc.upenn.edu/LDC2012T13 does contain the folder:

```
data/email/source/source_original
```

But how the raw source was segmented into sentences? How was this segmentation compared with the golden annotation of the sentences?

**Comment by manning** [comment]
The starting point was indeed to use the source/source_original material from https://catalog.ldc.upenn.edu/LDC2012T13  in a semi-automatic process. We were using the sentences as segmented by LDC2012T13 and used the source_original files to reconstruct the original form of tokens as opposed to their "normalized" form that LDC uses in the _text_ascii_tokenized and penntree folders. Since we retokenized with CoreNLP tools, we did note about half a dozen clear failures to sentence segment and our intention is to fix those someday, but we were initially somewhat reluctant to make the sentence splits incompatible with those in the LDC corpus.

**Comment by arademaker** [comment]
> We were using the sentences as segmented by LDC2012T13 and used the source_original files to reconstruct the original form of tokens as opposed to their "normalized" form that LDC uses in the _text_ascii_tokenized and penntree folders.

Can you be more specific? This is probable relevant to #283 that I just opened.
