### ISSUE TITLE
Suspicious advcl dependents of PRONs

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#269]
http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61b2bd25748b8

- "**those** making the charges"—should be `acl`? `acl:relcl`?
- Depictives should be `acl` if optional, `xcomp` if licensed by the matrix verb
   * "Imagine **yourself** sitting on the beach"—`xcomp` I think (verbs of perception: *picture, imagine, find, see, feel X Ying*)
- "What if": EWT—2 analyzed with `advcl`; GUM—1 analyzed with `advcl`, 1 with `dep`

**Comment by amir-zeldes** [comment]
* those making the charges - yes, acl IMO
  * Imagine yourself sitting on the beach - agreed, xcomp
  * What if - I think advcl is right, since "what" here stands for a whole predication, short for "what would it be like/what would happen..." (similar to how predicative nouns can take obl, not nmod, if it is expanding on their predication)

I'll fix the dep case in GUM. I see there's another advcl case in GUMReddit as well, and EWT is already advcl, so they'll all be consistent!

**Comment by nschneid** [comment]
Depictive clauses addressed in #292

**Comment by nschneid** [comment]
Not sure what to do with "if we lose Dean (which we will if we don't pay 65k + 10k)". Leaving it alone.

**Comment by nschneid** [comment]
This issue is a special case of #259
