### ISSUE TITLE
"Have" with object and predicate complement

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#285]
There are a few uses of "have" with a complement clause or result predicate as well as an object. I assume the predicative/result part (bold below) should be `xcomp`? That is the predominant analysis, but there are a number of annotations where the result is `ccomp` (and the object of the matrix verb is typically analyzed as its `nsubj`).

- 50 [EWT ccomp cases](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61d66d9910030)
- 5 [GUM ccomp cases](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61d66daa6b66f)

### Causative

- have my tonsils **removed**; have the final comments **in** by sunday; have them **rolling in the aisles**
  * cf. get my tonsils removed
- have him **leave**
  * cf. make him leave (but interestingly: He was made/*had to leave)

### Existential-experiential? Subject is not causing the result but is somehow affected

- we have a CPA, Larry Lewis, **working with us**
- How do you feel about having a lot of your work **overshadowed by the Mets work**?

**Comment by amir-zeldes** [comment]
I agree the GUM cases are all errors except possibly:

  * the participant group had mean and standard deviation 60.23 (64.75) respectively, while the control group was 20.00 (42.65).

I'm not sure xcomp is better here, since the subordinate predication is rather strange to begin with. I mean, it's not that they had the mean, and as a result it became 60.23, or that they made it so. Maybe it's more like ECM, like "they saw the mean being 60.23", where the mean just is 60.23, and there is no causative or resultative meaning.

This is a bit different in the last EWT examples (the former are also errors IMO): in "we have a CPA", they really possess that CPA. The overshadowed example I think is xcompier than the other doubtful cases, because it feels like xsubj to me.

**Comment by nschneid** [comment]
Yes we can talk about employment as possession, but "We have a CPA **working with us**" is not far removed from one of my favorite constructions—"We have a plane **to catch**" (or: "We have a plane waiting for us"), which does NOT entail that we possess a plane. :) I would say closer paraphrases are "There is a CPA working for us", "There is a plane for us to catch", "There is a plane waiting for us".

**Comment by nschneid** [comment]
Agreed that the standard deviation sentence is weird. Sort of elliptical scientific jargon for "standard deviation *of* 60.23".

**Comment by amir-zeldes** [comment]
Yeah, "plane to catch" is definitely adnominal `acl`, so maybe CPA is the same too.

**Comment by nschneid** [comment]
*It is a plane to catch that we have.

**Comment by nschneid** [comment]
Perhaps a better query: http://universal.grew.fr/?custom=634616bb7554e

**Comment by amir-zeldes** [comment]
I think these should be xcomp.

**Comment by nschneid** [comment]
So "have [Laura]obj [sign]xcomp" not "have [[Laura]nsubj sign]ccomp"?

- [ ] Also to fix: a couple of "make you feel" tokens in http://universal.grew.fr/?custom=63a386b28f636

**Comment by nschneid** [comment]
"have" should almost never have a `ccomp` dependent, which made these errors easy to find.

For "have no idea/clue": #300

Left alone "rumor had it/expl that...", which looks like extraposition.
