### ISSUE TITLE
Is "wtf" a pronoun?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#294]
If so, should it be marked with [Style](https://universaldependencies.org/u/feat/Style.html)`=Expr`?

**Comment by amir-zeldes** [comment]
I understand the principle of decomposing acronyms, but in this case I think as a user it would surprise me a lot. Maybe INTJ?

**Comment by nschneid** [comment]
I should have given an example: the sentence is

- Wtf is this?

which doesn't work grammatically without a nominal. Yes, it can be INTJ in other contexts.

**Comment by amir-zeldes** [comment]
Ooh, that's a tough one, because that actually represents the WH element for that question... I'm not sure if POS tags have to reflect the argument structure as solidly as the tree (which will surely have WTF as the predicate, just like "what"), but there is still a morphological criterion that could say this is something other than a pronoun. However I also don't know what to call it...

**Comment by AngledLuffa** [comment]
In the context given, I would say that is absolutely an interrogative WH pronoun.  It is unfortunate the only example of it is in the test set, as that means our models have no hope of getting it right

**Comment by nschneid** [comment]
Yes I agree
