### ISSUE TITLE
Reflexive/emphatic pronouns

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#295]
All are currently `PronType=Prs`. The ones that are emphatic should be changed to [PronType](https://universaldependencies.org/u/feat/Reflex.html)`=Emp`. The ones that are true reflexives should add `Reflex=Yes`.

**Comment by nschneid** [comment]
@dan-zeman The docs for [PronType](https://universaldependencies.org/u/feat/PronType.html) and [Reflex](https://universaldependencies.org/u/feat/Reflex.html) are not 100% clear on the relationship between them. I am guessing emphatic forms should have just `PronType=Emp` while the other reflexives should have `PronType=Prs|Reflex=Yes`, is that correct?

(Note that there are a few instances of reflexive forms being used in place of personal pronouns for politeness, e.g. "I think for starters, **myself** and those of you who believe in God could say a special prayer for them." These are tagged like the other non-emphatic reflexives.)

**Comment by dan-zeman** [comment]
I think that the original idea was that `Reflex` is orthogonal to `PronType` because several pronoun types can have also a reflexive subtype, hence it is a separate feature. Now I cannot recall anything else than "normal" reflexives and possessive reflexives, and since possessivity has been also made orthogonal, maybe it wasn't necessary to separate reflexives... but that does not seem like something we should change after it has been in the guidelines for 7 years. You always should have a `PronType`, so you either have `PronType=Prs|Reflex=Yes`, or `Poss=Yes|PronType=Prs|Reflex=Yes` (the latter not occurring in English).

All this is about word types, without looking at their actual function in the sentence. Reflexive clitics in European languages often have a wide array of possible functions (middle, passive, inchoative, impersonal), which can be distinguished by deprels, but I would still keep `Reflex=Yes` for them so they can be easily identified. Besides that, reflexives in some languages are also used for emphasis (while other languages have separate emphatic pronouns), and in some languages they signal reciprocity (while other languages have separate reciprocal pronouns). I would be quite fine with calling the pronoun reflexive even in these contexts (this is definitely what we do with reciprocally used reflexives in Czech; we don't use them for emphasis). But if you can and want to distinguish emphatic contexts by `PronType=Emp`, then I guess it's not wrong.

**Comment by nschneid** [comment]
Do you know of languages that use `PronType=Emp|Reflex=Yes`? If so we should definitely adopt that in English.

It wasn't clear from the docs whether `Reflex=Yes` meant *truly* reflexive uses of such pronouns, or referred to the forms of pronouns that are *canonically* reflexive (thus also including emphatic uses whose antecedent need not correspond to the subject, e.g. "I met the president himself"). I don't have a preference one way or another.

**Comment by dan-zeman** [comment]
> Do you know of languages that use `PronType=Emp|Reflex=Yes`?

It is used in Armenian (http://hdl.handle.net/11346/PMLTQ-R3LV). It could be in others but I stopped searching when I found the first instance.

I tried to make the documentation of `Reflex=Yes` clearer, thanks for reporting.
