### ISSUE TITLE
Gerund vs. Present Participle

### ISSUE THREAD

**Issue by kanayamah** [UniversalDependencies/UD_English-EWT#305]
Some verbs right after `be` have `VerbForm=Ger`, 
http://match.grew.fr/?corpus=UD_English-EWT@2.9&custom=620291ff9983c

but shouldn't most of them have `Tense=Pres|VerbForm=Part`?

**Comment by nschneid** [comment]
Correct. I think these queries are more precise:
[query 1](http://match.grew.fr/?corpus=UD_English-EWT@2.9&custom=620330059f22c)
[query 2](http://match.grew.fr/?corpus=UD_English-EWT@2.9&custom=620330b8d8678)

**Comment by nschneid** [comment]
In GUM, the distinction is purely whether the VBG has a "be" aux: https://universal.grew.fr/?custom=6577114a092c3

This targets most of the VBGs in the progressive construction, but misses ones that are auxes themselves (progressive passive "was being": https://universal.grew.fr/?custom=657712523998f).

**Comment by amir-zeldes** [comment]
Oh yeah, I can fix that in GUM.

**Comment by nschneid** [comment]
Now that we've standardized the treatment of passives I guess we can say now that

- VBG + `Voice=Pass` => `Tense=Pres|VerbForm=Part`
- VBG with `aux` dependent whose lemma is "be" => `Tense=Pres|VerbForm=Part`
- other VBG => `VerbForm=Ger`

Am I missing anything? What about VBG xcomps without any aux (I caught him **taking** money)—should that be considered progressive and therefore a participle? Or advcls like "**Seeking** recognition beyond the Prague area, he submitted a score of his First Symphony"?

**Comment by nschneid** [comment]
Honestly since morph feats are mainly there to explain how the form fits into a paradigm, I wouldn't mind calling all of them participles, assuming the UD validator is OK with that. The most gerund-like VBGs (with a det or nmod dependent) are rare and it's arguably a continuum—I don't see a need to try to split hairs in the features.

**Comment by nschneid** [comment]
@amir-zeldes thoughts?

**Comment by amir-zeldes** [comment]
I'm pretty happy with VerbForm=Ger as it is TBH. Gerunds without an auxiliary which are not nouns are more or less on par with infinitives, as your xcomp example demonstrates, and we have VerbForm=Inf, so why not? It's different from participles which are more like adjectives, and also different from the cases with articles, which are anyway tagged as nouns and therefore don't get VerbType ("the writing" etc.) If it ain't broke...

**Comment by nschneid** [comment]
So our current policy is that VerbForm=Part applies in the progressive construction ("he is seeking recognition"). Isn't that essentially the same as the advcl usage ("Seeking recognition, he...")?

The universal guidelines for VerbForm=Ger discourage it. Looking at how the term is traditionally used for English, [Merriam-Webster](https://www.merriam-webster.com/dictionary/gerund) says:

> any of several linguistic forms analogous to the Latin gerund in languages other than Latin
especially : the English [verbal noun](https://www.merriam-webster.com/dictionary/verbal%20noun) ending in -ing that has the function of a [substantive](https://www.merriam-webster.com/dictionary/substantive#h2) and at the same time shows the verbal features of tense, voice, and capacity to take adverbial qualifiers and to govern (see [govern sense 4](https://www.merriam-webster.com/dictionary/govern)) objects

Wikipedia [says](https://en.wikipedia.org/wiki/Gerund#Traditional_use) the term "gerund" in English would apply to subject/complement uses but not adverbials, adnominal clause modifiers, or progressive clauses. (But the article also highlights controversy on the applicability of the term to English.)

I guess these sources are basically saying, if an *-ing* verb retaining some verbal properties occurs in a context that licenses nouns (like subject or complement in a clause, i.e. `csubj`, `xcomp`), it is a gerund, and otherwise it is a participle.

So I guess my question is, should we follow traditional English grammar and try to echo a gerund vs. participle distinction borrowed awkwardly from Latin grammar? Or should we treat features in UD as predicting the form, not grammatical function, in which case the distinction is unnecessary? If it's the former, I do think we need to consult English grammar traditions and not make up a completely new way to draw the line, as this will only add to the confusion.

**Comment by amir-zeldes** [comment]
Those are all good points and I don't feel passionately about it as long as we can automate it. Between ignoring it and following traditional grammar I guess I would opt for the latter, since it's quite possible proponents of some variety of Basic Linguistic Theory will care about this distinction, and if we distinguish Inf as a form I find Ger good to have as well. 

Can you formulate rules for when it should be used, ideally expressible as depedit rules?

**Comment by nschneid** [comment]
What about this split (see comments)?: https://universal.grew.fr/?custom=65fcbcfe03f2b

**Comment by nschneid** [comment]
IOW, the decision list:
1. If it has an aux(:pass) dependent: `VerbForm=Part`.
2. If it attaches as `acl|acl:relcl|amod|appos|ccomp|compound|csubj|csubj:pass|nsubj|obj|xcomp` (i.e., a predicate's subject or complement, or an adnominal modifier): `VerbForm=Ger`
3. If it attaches as `conj` and its head has an aux(:pass) dependent: `VerbForm=Part`.
4. If it attaches as `conj` and its head attaches as `acl|acl:relcl|amod|appos|ccomp|compound|csubj|csubj:pass|nsubj|obj|xcomp`: `VerbForm=Ger`.
5. Otherwise: `VerbForm=Part`.

I haven't tested this in depth but I'm at least more comfortable with this narrower scope of the gerund category than the current policy.

**Comment by amir-zeldes** [comment]
OK, implemented for GUM morphology, should propagate to GUM and GENTLE in the next release.

**Comment by nschneid** [comment]
That will get most of them but I think [these 11](https://universal.grew.fr/?custom=66035457ee3a5) will be mislabeled absent a check for the head of a `conj` having an `aux.*|cop` dependent. That can go below the current rules I think.

**Comment by nschneid** [comment]
https://github.com/UniversalDependencies/UD_English-EWT/blob/c6ed51e29ce0275ad2d960a3da3df26b1e604676/not-to-release/tools/gerpart.ini#L1-L9

**Comment by amir-zeldes** [comment]
> That will get most of them but I think [these 11](https://universal.grew.fr/?custom=66035457ee3a5) will be mislabeled absent a check for the head of a `conj` having an `aux.*|cop` dependent. That can go below the current rules I think.

OK, I can just reorder the rules like this to catch the aux on the parent first:

```ini
xpos=/VBG/	none	#1:morph+=VerbForm=Part
xpos=/VBG/&func=/acl|acl:relcl|amod|appos|ccomp|compound|csubj|csubj:pass|nmod|nsubj|obj|xcomp/	none	#1:morph+=VerbForm=Ger
xpos=/VBG/;lemma=/be/&func=/aux.*/	#1>#2	#1:morph+=Tense=Pres|VerbForm=Part;#1:storage=hasaux
xpos=/VBG/&lemma=/be/&func=/aux.*/	none	#1:morph+=Tense=Pres|VerbForm=Part;#1:storage=hasaux
func=/acl|acl:relcl|amod|appos|ccomp|compound|csubj|csubj:pass|nmod|nsubj|obj|xcomp/&storage!=/hasaux/;xpos=/VBG/&func=/conj/	#1>#2	#2:morph+=VerbForm=Ger
```

**Comment by nschneid** [comment]
1) I think I checked and on the conj-parent it's not just "be" as `aux`, though, it's also `cop` ("he is young and working") and other kinds of auxes
2) Right now `Tense=Pres` won't be set for the ones that are participles by default from the first rule

**Comment by nschneid** [comment]
If I'm reading that right it treats `cop` the same as `aux` across the board, not just for the `conj` cases. I think that would categorize sentences of the form "X is like VBG" or "one important factor is being young" as Part, but I suspect Ger is better.

> "Two important factors are being young and working out"?

Should there be a rule that deals directly with VBG-[conj]->VBG where the second VBG has neither cop nor aux? I guess the right thing to do would be to copy the features of the first onto the second, on the assumption that any cop/aux on the first one can be understood as shared (scoping over the whole coordination).

**Comment by nschneid** [comment]
Modified/added coordination rules within your version (comments inline). This seems to work well on EWT:

```ini
# unchanged rules
xpos=/VBG/	none	#1:morph+=Tense=Pres|VerbForm=Part
xpos=/VBG/&func=/acl|acl:relcl|amod|appos|ccomp|compound|csubj|csubj:pass|nmod|nsubj|obj|xcomp/	none	#1:morph+=VerbForm=Ger;#1:morph-=Tense
xpos=/VBG/;func=/aux.*/	#1>#2	#1:morph+=Tense=Pres|VerbForm=Part;#1:storage=hasaux
xpos=/VBG/&func=/aux.*/	none	#1:morph+=Tense=Pres|VerbForm=Part;#1:storage=hasaux

# added 2nd storage condition
func=/acl|acl:relcl|amod|appos|ccomp|compound|csubj|csubj:pass|nmod|nsubj|obj|xcomp/&storage!=/hasaux/;xpos=/VBG/&func=/conj/&storage!=/hasaux/	#1>#2	#2:morph+=VerbForm=Ger;#2:morph-=Tense

# added rule for coordination with an adjective/participle
upos=/ADJ|VERB/&xpos!=/VBG/;xpos=/VBG/&func=/conj/	#1>#2	#2:morph+=Tense=Pres|VerbForm=Part

# added rules: VBG-[conj]->VBG where the second VBG has neither cop nor aux: copy feats from first VBG
xpos=/VBG/;xpos=/VBG/&func=/conj/;func=/(cop|aux.*)/	#1>#2;#2>#3	#2:storage=hascopaux
xpos=/VBG/&morph=/.*VerbForm=Ger.*/;xpos=/VBG/&func=/conj/&morph!=/.*VerbForm=Ger.*/&storage!=/hascopaux/	#1>#2	#2:morph+=VerbForm=Ger;#2:morph-=Tense
xpos=/VBG/&morph!=/.*VerbForm=Ger.*/;xpos=/VBG/&func=/conj/&morph=/.*VerbForm=Ger.*/&storage!=/hascopaux/	#1>#2	#2:morph+=Tense=Pres|VerbForm=Part
```

**Comment by nschneid** [comment]
Looking again in EWT, I see some things tagged as gerunds that probably shouldn't be:
- He mentions his wife's death **having** an effect on him. (ccomp: has a non-copular nsubj, "death")
- I for one was very happy to hear about your **quitting** smoking. (advcl: has a non-copular nsubj, "your")
- [It] would have us **reporting** tomorrow's activity on Monday (xcomp: cannot substitute a nominal in this construction)

That said, I suspect there is no simple set of rules for the present participle/gerund distinction that will work perfectly, so I'm inclined to stick with what we have.

**Comment by nschneid** [comment]
documented in the English guidelines
