### ISSUE TITLE
Lemmatization of temporal "a.m."/"p.m."

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#334]
It is not completely consistent [within EWT](http://universal.grew.fr/?custom=62d30e5fe0979). I propose we standardize on "a.m." and "p.m." as lemmas, as these strings are less ambiguous than "am", "AM", or "PM". @amir-zeldes are you OK with that? There are just 12 occurrences in GUM.

Related: #131

**Comment by amir-zeldes** [comment]
Sure, I don't mind going with "a.m." and "p.m.", though I suspect there are larger issues regarding acronyms here. Do we plan to standardize "U.S." and "US"? How about "US" and "USA"? Is there a unifying principle? (e.g. always include/remove periods in acronyms)

**Comment by nschneid** [comment]
Not sure there is/should be a unifying principle since including periods is more or less conventional depending on the expression. Open to suggestions though.

**Comment by amir-zeldes** [comment]
OK, for now I can make a.m./p.m. consistent, since consistency is always better than not, but I think there are more forms we need to think about moving forward. 

TBH my gut feeling is that we should just go with the "majority" form (established how is an open question), since I think FBI is much more expected than F.B.I., but G.I. looks better than GI - maybe we could also use an established style guide from some press... Those are more or less arbitrary too, but you can at least point to them and say that's what we're using.
