### ISSUE TITLE
SCONJ should correspond to xpos=IN

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#457]
- [x] [11 EWT errors](https://universal.grew.fr/?custom=653c1bbe84521)
- [ ] [12 GUM errors](https://universal.grew.fr/?custom=653c1bdabb862)

(This is relevant to adding `Voice=Pass` #290 as the validator doesn't allow SCONJ to have a `Voice` feature.)

**Comment by nschneid** [comment]
I guess the `goeswith` one is actually correct. Fixed the others in EWT.

**Comment by amir-zeldes** [comment]
OK, fixed GUM except for the VBGs, they're intentional; but that shouldn't matter if we're now not doing Voice=Act.

**Comment by nschneid** [comment]
I thought we decided the VBGs should be tagged VERB (but the deprel of `mark` is correct).

**Comment by amir-zeldes** [comment]
Oh I see, I guess that makes sense. I'll do that for GUM & co. too

**Comment by nschneid** [comment]
@amir-zeldes There's still a slight divergence between GUM and EWT here: EWT uses ADJ for "such" in the fixed expression "such as". (The expression as a whole functions as `mark`, so `ExtPos=SCONJ` would be appropriate.)

**Comment by amir-zeldes** [comment]
I see, OK, I can still change this. I guess the simplest solution for absolute parity would be to use the same upos script on both datasets, but I think there are some manual upos edits in EWT, right?

**Comment by nschneid** [comment]
I don't have a UPOS generation script for EWT—I have been editing whatever was in the .conllu over the years. If you wanted to run the GUM one on EWT that would make for an interesting comparison.

**Comment by amir-zeldes** [comment]
Sure, it's mostly just depedit, though it's possible there's some other tinkering going on in the buildbot, I'd have to look. It seems like a hassle to maintain both upos and xpos, and since I take it xpos is pretty high quality, I like to correct just that, and project to upos using the tree. 

BTW GENTLE also has "such that", I guess we want that to be ADJ SCONJ? Currently they're annotated as mark sisters, since there is no fixed "such that" on the fixed list.

**Comment by nschneid** [comment]
Hmm, EWT just has ['are such that'](https://universal.grew.fr/?custom=6542666b50773) which is not quite the same. When it acts as `mark`, I would probably include "such that" on the fixed list if "such as" is there. I don't think it makes sense to say that "such" can independently be `mark`.

**Comment by nschneid** [comment]
"so that" is also on the fixed list BTW. Cf. #400

**Comment by nschneid** [comment]
Yeah. There are even a few fixed expressions in EWT that never got added to the list for some reason. At some point we should discuss those too.

**Comment by nschneid** [comment]
UniversalDependencies/UD_English-GENTLE@2103015

**Comment by amir-zeldes** [comment]
OK, I changed GENTLE trees to match that, and added it to the fixed list in the UD guidelines and GUM wiki. I feel a bit bad for parsers testing on GENTLE, which is meant to be an OOD test set, since we just introduced a fixed expression that is totally absent from GUM/EWT, meaning it would be unreasonable to expect it to be predicted correctly... But such is life I suppose!

**Comment by amir-zeldes** [comment]
Thanks for adding the commits hashes - I think this is good to close!
