### ISSUE TITLE
Use multiple-word tokens for "don't" and similar

### ISSUE THREAD

**Issue by foxik** [UniversalDependencies/UD_English-EWT#5]
I assume that in "ideal" word, `don't` would be tokenized as

```
1-2   don't
1     do
2     not
```

I understand that the current tokenization follows the "new" Penn Treebank style. But I believe that it could be improved using the multiword tokens available in CoNLL-U as follows. Instead of

```
1   do
2   n't
```

we could use

```
1-2   don't
1     do
2     n't
```

That is backward compatible (the words are still the same), but it is obvious that the original text was "don't" and not "do n't".

I believe it would be enough to add the multiword tokens by a set ot fixed rules. Again, if you are interested, I am happy to help in any way.

**Comment by manning** [comment]
Sure, we'd be very happy to have this too! Thanks!  This would be an upgrade, exploiting CoNLL-U. I think this would definitely have to be an after release 1.2 upgrade.

**Comment by foxik** [comment]
I agree that this should probably be performed after the 1.2 release -- the resulting CoNLL-U file will use nontrivial feature, which might interfere with your pipelines.

I am happy to provide the rules for the multiple-word tokens, but any English tokenizer already has a list of those. But I am happy to help in any way.

BTW, adding multiple-word tokens will interact with the `SpaceAfter=No` a bit -- the `SpaceAfter=No` should be specified for the whole multi-word tokens and not for the words of such tokens, so
  - the `SpaceAfter=No` will have to be removed from the all-but-last words of a multi-word token
  - the possible `SpaceAfter=No` feature of the last word of a multiword token will have to be moved to the multiword token itself

**Comment by jeanm** [comment]
Hi! I am keen to use this treebank for my research, and I would also like to see the proposed changes implemented. 

@foxik, are you working on this? I am happy to have a go at it if you are currently busy.

**Comment by manning** [comment]
@jeanm: If someone else wanted to take this on, you'd be most welcome. 😄  Since I there isn't any labor force to do this at the moment here. But, two comments: (i) If you're interested, let us know, since the right thing to do would be to make the changes in the original. We maintain separate files in a different repository for each "document" reflecting the original LDC files, and then just concatenate them to produce these files. We'd want the changes made to the original, or they'll be overwritten. (ii) Long term, I think the right thing to aim at would be to make use of the `source_original` files in the original LDC distribution, since not only does that give the correct original spacing but also it would eventually seem better to undo their ASCII-fication. But I'd be happy to have an interim fix that just dealt with the commonest cases of contractions.

**Comment by foxik** [comment]
@jeanm I am currently not working on this, but I am still interested in the feature.

@manning If you can tell me where are your intermediate files, I would be happy to create a patch :-)

There is still a question whether we want to do this "backward-compatible" using
```
1-2 don't
1 do
2 n't
```
or "correctly" using
```
1-2 don't
1 do
2 not
```
I vote for the latter, but if you favour the former, I still prefer it to the current situation.

The 1.3 will be released soon -- the proposed changes will of course not go to 1.3. Is it fine if I do the patch now, or it would be better for you to receive the patch after 1.3 is released?

**Comment by nschneid** [comment]
Would this also apply to other contracted forms like `I've`, `he's`, and `you'll`? And the possessive clitic (`'s`, etc.)?

**Comment by foxik** [comment]
I am not a native English speaker, so I am not sure. Personally I would tokenize the first three as multiword tokens
```
I've   -> I have
he's   -> he (is|has)
you'll -> you will
```
and I would leave `'s` as is.

Interestingly, `he's` is not unique, so it would have to be disambiguated (and the tokenizer would have to become much more clever).

**Comment by jnivre** [comment]
The ambiguity could be taken as an argument that we should leave the word as "'s" and disambiguate only in the lemma.

**Comment by foxik** [comment]
So it would look like `he's -> he s`? Or should we not use multiword token at all?

Nevertheless, not disambiguating it in the tokenizer is definitely the right way :-)

**Comment by jeanm** [comment]
> So it would look like `he's -> he s`?

I'd say `he's -> he 's`, which is the way it's currently done.

**Comment by foxik** [comment]
@jnivre @jeanm and would you use multiword token or not? I currently see three possibilities:
1) current
```
1 he
2 's
```
2) multiword token without apostrophe
```
1-2 he's
1 he
2 s
```
3) multiword token with apostrophe
```
1-2 he's
1 he
2 's
```

Personally I would vote for 2), so that it would be consistent with the hypothetical:
```
1-2 I've
1 I
2 have
```

**Comment by jeanm** [comment]
I do not have a strong opinion on this, but I would lean towards your third suggestion. Two reasons:
 * Having a tokenizer perform lossy transformations on the source text seems a bit iffy to me.

  If we take your previous example of `don't` becoming `do` and `not`, then any instances in the source text of `don't` and `do not` would become, apart from the presence of the multi-token line, indistinguishable. This feels wrong, since their usage in English is not the same: in the interrogative form one can say e.g. `Don't you like it?`, but not `Do not you like it?`.
 * It might be nice to remain as consistent as possible with the old Penn Treebank tokenisation scheme, and previous versions of this dataset (?)

Here's A Perl script to add multi-token lines for `Xn't`, according to your third option:
```
perl -i -0pe "s/\n(([0-9]+)\t(ai|are|ca|could|dare|did|does|do|had|has|have|is|might|must|need|ought|sha|should|was|were|wo|would)\t[^\n]+\n([0-9]+)\tn't\t)/\n\2-\4\t\3n't\t_\t_\t_\t_\t_\t_\t_\t_\n\1/ig" <FILE>
```

**Comment by jnivre** [comment]
I also vote for 3. It is most consistent with de facto standards.

**Comment by foxik** [comment]
Then 3 it will be.

@jeanm Note that you have to deal with `SpaceAfter=No` feature too -- it should be originally present for the first token and removed during transformation, and if `SpaceAfter=No` is present for the second token, it has to be moved to the multiword token instead.

**Comment by jeanm** [comment]
Thanks, you're right!

> if `SpaceAfter=No` is present for the second token, it has to be moved to the multiword token instead.

Should it be *moved* or *copied* though? The specification doesn't mention that as far as I can see.

Here's an updated perl script that *copies* `SpaceAfter=No`: https://gist.github.com/jeanm/42c474bcb5598df428f34d7879ea9d4c
In order to have it moved instead, just replace the second `\7` in the penultimate line with `_`.

This assumes that the [MISC field](http://universaldependencies.org/format.html) can only contain `SpaceAfter=No`. I think that's currently the case for this dataset. If it isn't, things will be slightly more complicated.

**Comment by foxik** [comment]
In 1.3, the only values of MISC column are `_` and `SpaceAfter=No`, so that should be fine.

The `SpaceAfter=No` should be *moved*, the [SpaceAfter documentation](http://universaldependencies.org/format.html#untokenized-text) states that `SpaceAfter` applies to token level and not word level (and demonstrates that on an example at the end of the paragraph).

**Comment by jeanm** [comment]
Ok, I fixed the script 👍

**Comment by nschneid** [comment]
We finally got around to this: #100 and #159!
