### ISSUE TITLE
"none" as plural?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#513]
"None" is compatible with singular or plural reference. When it triggers plural agreement on the verb, should it be tagged as NNS/Number=Plur?

Currently it's always NNS/Number=Sing ([EWT](https://universal.grew.fr/?custom=65ea4e1b33bb6), [GUM](https://universal.grew.fr/?custom=65ea4e41452e4)).

I suppose trying to disambiguate it would be like GUM disambiguating the number of "you"...but I'm not sure it's worth it.

**Comment by amir-zeldes** [comment]
Mmm, my gut feeling is that this is not a morphosyntactic number category here. I could be swayed, but I would point out we don't treat committee nouns as having different morphological categories based on actual token-agreement. We could put these in the same bag. I feel 'you' is more interesting because it's part of a paradigm that does distinguish number, so it's more like disambiguating a paradigmatic syncretism.

**Comment by nschneid** [comment]
OK
