### ISSUE TITLE
Rightward pointing csubj, no expletive

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#524]
Several errors:

- [x] [EWT](https://universal.grew.fr/?custom=663717b09549d)
- [x] [GUM](https://universal.grew.fr/?custom=663717d7c9fa1)

Half of the EWT ones are covert extraposition with pro-drop of the expletive subject ("Took me a little longer to review") or subject+copula ("Good to hear from you").

Should any of these be `dislocated`?
- A real pleasure training with Natasha. ("It is a real pleasure training with Natasha" or "A real pleasure, training with Natasha"?)
- What a joy to stroll off historic Canyon Road. ("What a joy it is to stroll" or "What a joy, to stroll"?)
- Not the smartest move to take off on a worldly adventure

**Comment by amir-zeldes** [comment]
I think 4 of the GUM ones are errors, will fix. The rest seem legitimate (notice the recurring analysis of "no matter" clauses, which I think have a postposed csubj if the subordinate clause is finite, i.e. "no matter/advcl who goes/csubj" = "who goes/csubj doesn't matter")

>Should any of these be dislocated?

I wouldn't go that way since there is no double realization. I'd just say this is a genuine case in English where only the heavy constituent is realized, so expl was skipped (assuming an elliptical expletive seems odd).

**Comment by nschneid** [comment]
I'm OK with csubj instead of dislocated.

Still a null subject IMO, taking an English-centric view of subjecthood where pre-verbal expl = expletive subject. Just "it" or "it"+copula may be omitted in certain genres/causal registers, e.g. diary style. It-expletives are not always optional though: _*John who lost the keys._ cannot be short for _It was John who lost the keys._ (cleft).
