### ISSUE TITLE
"give s.b. a hand/leg up" idiom

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#531]
What is the attachment of "up"?

It feels resultative. "A leg up was given..." sounds OK though.

**Comment by nschneid** [comment]
"the way in"

"the road home"

advmod???

**Comment by nschneid** [comment]
@amir-zeldes thoughts?

**Comment by amir-zeldes** [comment]
I'd say in "give s.b. a leg up", up/xcomp. I you literally have "a leg up was given", then I guess advmod is more appropriate, since then the syntax suggests it's adnominal. But in normal usage, I would expect the literal tree, where 'up' is a secondary prediction (the figurative leg is now up).

The way in and road home should both be advmod IMO, since we're in adnominal territory again.

**Comment by nschneid** [comment]
> I'd say in "give s.b. a leg up", up/xcomp.

But: *A leg was given up (to s.b.). If it were xcomp I think we'd expect that to work.

- I painted the wall blue / The wall was painted blue / *The wall blue was painted

Can you think of a clear example of a double object plus xcomp resultative? I don't see any results with [that configuration](https://universal.grew.fr/?custom=665f7c861e119).

**Comment by amir-zeldes** [comment]
> But: *A leg was given up (to s.b.). If it were xcomp I think we'd expect that to work.

Not all idioms are passivizable (e.g. bucket was kicked by John)

> Can you think of a clear example of a double object plus xcomp resultative?

No, I can't TBH. If you prefer adnominal advmod for "give someone a leg up" I don't think it's terrible either, it's such a niche fixed expression anyway, there's no really satisfying way I can see to analyze it compositionally.

**Comment by nschneid** [comment]
Yeah my intuition is that "a leg up" is pretty institutionalized at this point so we might as well call it advmod.
