### ISSUE TITLE
post-nominal "else": ADJ or ADV?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#556]
One discrepancy between EWT and GUM is the treatment of PRON + "else": GUM treats "else" as always ADV, whereas EWT treats it as ADJ if occurring with a nominal.

It appears that LDC annotators followed different practices in different treebanks.

Looking in original EWT:
<img width="290" alt="image" src="https://github.com/user-attachments/assets/51d5700e-a9bf-44b8-bcee-0c2d8ef1ee56" />

vs. OntoNotes 5:
<img width="290" alt="image" src="https://github.com/user-attachments/assets/e9ccad65-513c-4bef-b9c9-c6cb3e48146b" />

I personally don't have an opinion on this..."else" is simply a weird word. @amir-zeldes I assume you'd prefer uniform ADV/advmod?

**Comment by amir-zeldes** [comment]
Yeah, I've always considered it to be an adverb. Properly speaking it's an etymological genitive nominal (it's a cognate of the stem of the Latin "al." plus genitive -s, i.e. "of another"), but synchronically it's a sui generis, and even if we went by etymology I guess it's "oblique-y", so advmod fits better than amod. Plus that seems to be the majority usage in ON, so why not.

PS - RE sui generis if we're not sold on it being unique, I guess it sort of alternates with "otherwise" in some positions, e.g. "anything else" is more or less like "anything otherwise". Either way speaks more for RB/advmod IMO.
