### ISSUE TITLE
Some sentences with CopyOf= in MISC have empty HEAD and DEPREL

### ISSUE THREAD

**Issue by venkatasg** [UniversalDependencies/UD_English-EWT#61]
I'm not sure if this is an error or a feature in new versions, so I apologize if I've made a mistake. There are a few sentences where(for example sent_id = reviews-363685-0017 in train) which repeat a previous word(with index 24.1 where 24 is index of previous word) with the HEAD and DEPREL columns left unspecified. The only information I can gleam from these sentences is that their last two columns, the last column being CopyOf followed by the original index of the repeated word. 

What purpose do these repetitions serve? Isn't it a violation of the annotation guidelines to leave the HEAD and DEPREL empty? I believe this has something to do with sentence coordination, although I don't understand the purpose.

**Comment by nschneid** [comment]
See http://universaldependencies.org/u/overview/enhanced-syntax.html and http://universaldependencies.org/format.html with respect to empty nodes. "Empty nodes must have non-empty ID and DEPS fields and empty fields (i.e. underscores) for HEAD and DEPREL, because they are only part of the enhanced dependency graph."

**Comment by venkatasg** [comment]
Thank you!
