### ISSUE TITLE
Analysis of "not"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#64]
There are currently quite a lot of "not" as ADV (about 80, if my quick script is accurate), but "not" and "n't" should always be tagged as PART, correct?

**Comment by dan-zeman** [comment]
It should be `PART`, according to the guidelines, http://universaldependencies.org/u/pos/PART.html#Examples

**Comment by nschneid** [comment]
Should "not" ever be treated as a coordinator? EWT has coordination analyses like

- Jack welch is the CEO of **GE, not/cc GM**.
- it's **a lifestyle not/cc [a resort area]**
- I found the hotel to be **amazingly clean, not/cc to/fixed mention/fixed [very well adorned with many pleasant surprises]**. 
- Prove, to your parents' satisfaction, that **you, not/cc they**, will be the one actually taking care of your new pet. 

The last one ("not they") is interesting because personal pronouns don't take adjectival modifiers, but they can take focus modifiers ("only they"), so maybe `advmod` is an alternative here.

Then there are correlatives like "not only...but also" and similar ("not by X but by Y").

As for the tag, it is currently CCONJ or ADV in some places, but I understand from the guidelines that it should be PART.

**Comment by amir-zeldes** [comment]
No, I don't think any of these are cc. They convey the usual negation, and they are in coordinating contexts (so their parent is conj), but that does not make them ccs: the coordinating element here is simply zero IMO, and notice you can insert "and" etc.: "CEO of GE (and) not GM". If "not" were the cc, it should not be possible to realize it a second time as "and".

**Comment by nschneid** [comment]
Good point. Would you use `advmod`?

**Comment by amir-zeldes** [comment]
Yes, that sounds fine!

**Comment by nschneid** [comment]
So none of these should be considered coordination at all, right?

Jack welch is the CEO of GE, not GM.: parataxis(GE, GM)?

If "and" were inserted I don't think that would change the construction: still a parenthetical/supplement.

**Comment by amir-zeldes** [comment]
The issue of adnominal parataxis is kind of murky IMO; my intuition in this case it to consider it a zero conj, but between clauses of course that would be parataxis. However for nominals you would lose the tracking of the deprel propagation: "not GM" is what Jack Welch is (not) the CEO of, which is clear if we use conj, but lost if we change to parataxis.

**Comment by nschneid** [comment]
Agreed that parataxis is generally murky. Morphosyntactically it is worth noting that this does not make a plural NP even when "and" is present:

- GE, and not GM, is the company he heads.

Also the position of the supplement is not fixed:

- GE is the company he heads, and not GM.

(It feels related to focus markers: only, too, etc.)

My guess is that supplements like this require anaphoric interpretation (to infer that "GM" is in alternation with "GE"), which is beyond the scope of UD.

**Comment by dan-zeman** [comment]
> this does not make a plural NP

Not all instances of coordination result in a plural nominal. The conjunction can be _or_ or _but_.

**Comment by amir-zeldes** [comment]
> Also the position of the supplement is not fixed

This is true of normal coordination as well:

  * I ate a pie yesterday and a waffle

**Comment by nschneid** [comment]
Fair enough. But wouldn't you agree that a comma or some sort of pause is required for

- It was a pie that I ate yesterday, and a waffle. (last part is sort of an afterthought)

Which is distinct from

- It was a pie that I ate yesterday, and a waffle that I ate today. (coordination, with RNR?)

**Comment by amir-zeldes** [comment]
I'm not sure if there is a pause there or how to identify/quantify it, but in any case that wouldn't play into it for me: for `conj` I think it's necessary that an explicit coordination is either there or at least possible (which it is) and that it saturates the same valency role (both are `obj` to the same verb node, "eay"). 

In the second example there is a second "eat", so that's different (and I would see it the same in the RNR case, if it was "and a waffle today", which should be conj to "ate1"+orphan). These would be parataxis for me:

  * It was a pie that I ate yesterday, it was a waffle that I ate today. (no coordination, no joint argstr)
  * It was a pie that I ate yesterday, a waffle today (same but RNR, so "today" is orphan, since there are two predications with disjoint temporal adjuncts)

I think the more general question here is "is zero adnominal coordination, where 'and' is insertable and a single role is saturated, parataxis or conj"? I see pros and cons for both: allowing conj without parataxis is a slippery slope, but parataxis where it is 100% the same as conj except the missing "and" prevents inferring argument propagation, a major use of conj.

PS - Dan may rightly remark that question belongs in docs :)

**Comment by nschneid** [comment]
OK. I don't know that I have the stamina to open up a broader discussion of parataxis vs. coordination right now, so for EWT purposes I'll go with the status quo (conj) in the structure, but fix the "not" because that just seems wrong as `cc` (and CCONJ is not supported by PTB guidelines so I'm not sure how that happened).

I will just flag here that #236 may be relevant.
