### ISSUE TITLE
Treatment of "compared to"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#78]
cf. https://github.com/UniversalDependencies/docs/issues/491

**Comment by nschneid** [comment]
The prevailing treatment seems to be that multiword "compared to"

- attaches to its complement as double `case` or double `mark`, depending on whether the complement is clausal
- the complement head attaches as `nmod` or `obl`
   * What is the right policy if there is an implicit predication? "great knowledge and prices compared to anyone in the industry"—really this means 'compared to anyone in the industry, THIS PLACE HAS great knowledge and prices'

There is a sentence with structural issues due to an omitted auxiliary: "and (WAS) used to compared to"

**Comment by amir-zeldes** [comment]
I'd vote for treating it as a content word with normal government (e.g. prepositional object as `obl`). It seems compositional and transparent to me, and the finite versions mean the same things:

  * I compared A to B - root(compared), obl(compared,B)
  * A is better when compared to B - advcl(better,compared), mark(compared, when)
  * Compared to B, A is better - advcl(better, compared)
  * A compared to B is a better option - nsubj(option, A), acl(A, compared)

The treatment of compared as advcl, acl, etc. is also justified by the guidelines that make it VBN, e.g. ability to introduce by-agent, compatibility with get-passive but not become, etc. (cf. Santorini 1990):

  * A was compared to B by many people
  * A got compared to B
  * But not: * A became compared to B

**Comment by nschneid** [comment]
> * Compared to B, A is better - advcl(better, compared)

I think the semantically closest paraphrase of this is "Relative to B, A is better". How would that be analyzed?

> * A compared to B is a better option - nsubj(option, A), acl(A, compared)

This might be paraphrased as "A rather than B" or "A instead of B".

Does "contrasted with" sound as natural in these usages? I'm not sure.

"Distinguished from" sounds less natural:

* ?Distinguished from B, A is better
* ?A distinguished from B is a better option

So there seems to be some grammaticalization, and the question is where we draw the line.

**Comment by amir-zeldes** [comment]
Since 'relative' is not a VVN, the morphosyntactic analogy isn't complete in this case, but I think the options are either `advmod` (saying that 'relative' works like 'relatively' or 'in a reative way') or `advcl`, assuming something like a silent 'being'. I think it's best to keep assumptions to a minimum and not invoke ellipsis if possible, so I would probably go with `advmod` (though I don't think that indicates what to do with 'compared').

"Contrasted with" is a better analogy structurally, and regardless of naturalness I would analyzed it the same if I saw one of those examples, i.e. as an `advcl`, because in being an adverbially used participle it has the function of a clause more unambiguously (without the need to imagine 'being'). Some examples of adverbial "contrasted with" from ENCOW:

  * Contrasted with the average MP , Nero himself was an enlightened philanthropist
  * Contrasted with the Greek , Luther 's translation seems ' pious '
  * West Columbia of a Half Century Ago Contrasted with the West Columbia of Today
  * Contrasted with Rangers ' current woes , which see McCoist pinning his hopes on the possible short-term return of Daniel Cousin , it is easy to see why the Ibrox men are now priced as long as 5 -1 to win a fourth successive SPL crown .

I didn't understand the argument about 'distinguished', though I also don't think it's lexicalized to that form as a participle - since it's compositional and inflects freely, it should not be `fixed` and the verbal head doesn't need to be `case`.

**Comment by nschneid** [comment]
I'm still not clear on the policy. We have:

- to-phrase attaching to "compared" as `obl` or `advcl` ([3 results](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61b4d40686a15&clustering=rel.label))
- double `case` analysis attaching as `obl` or `nmod` ([7 results](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61b4d30f2898f&clustering=rel.label))
  * Not sure if the `nmod` ones are correct—the "compared to" phrase seems almost paratactic, or perhaps licensed by the adjective:
     - **someone** fully trained and skilled compared to others
     - great **knowledge** and prices compared to anyone in the industry
     - a HUGE **number** compared to the others in the area

**Comment by amir-zeldes** [comment]
Looks like in GUM it's always advcl into compared, then obl+case for the argument, which makes sense to me because:

  * If it's tagged VERB+advcl then the argument should be obl
  * There are variants with mark (optional "(when) compared to")
  * Given some cases must be clausal, it makes life simpler to assume it's always clausal when used adverbially, and for GUM this interacts with RST, since the discourse segments follow RST-DT guidelines, in which "compared to" is a clause, and therefore a discourse unit.

**Comment by nschneid** [comment]
I wouldn't object to dropping the pseudo-preposition/double-case analysis (as LDC seems to have done per Chris's comment).

What should be the head of "compared" in the 3 sentences I posted above, though?

**Comment by amir-zeldes** [comment]
I would do:

  * advcl(trained, compared)
  * advcl(great, compared)
  * advcl(huge, compared)

**Comment by nschneid** [comment]
Oh boy, we have a torture test sentence that uses "compared" as a finite verb:

- one of the sales ladies was quite comfortable telling me how wrong I was about [how [another dress that I loved] compared [to one of her dresses]]

The current annotation has: telling -[ccomp]-> wrong -[acl:relcl]-> was -[advcl]-> compared, with the 1st "how" attaching as `mark` to "wrong" and the 2nd "how" attaching as `mark` to "compared". Is this correct? Or should there be a nonprojective analysis with "wrong" heading "was" as `cop` and "compared" as `advcl`? And should the first "how" attach as `advmod` instead of `mark` (it is a degree modifier of "wrong")?

**Comment by amir-zeldes** [comment]
Right, well, this is complicated enough that I think it deserves a full IAA test - I totally didn't parse what you say EWT did with this and just annotated the following from scratch, then I'll see what you're saying in more detail:

![image](https://user-images.githubusercontent.com/2188635/146612260-0a5fc4d2-5e6b-4349-b2db-6b889be6d00d.png)

**Comment by amir-zeldes** [comment]
So, huh, no, I seem to disagree with EWT: 

  * I don't think it's ccomp, because she telling me "(the way) how I was wrong" - what was being told to me is the wrongness, not the fact that I was wrong (a clause). Another way of paraphrasing this is: "she was telling me how wrong it is that I was" - in this case it would be ccomp, but the "that I was" with relative pronoun reveals that it's a free relative here IMO.
  * I took the "was" to be totally subordinate (how wrong it is that I was) so it doesn't get advcl to anything. "wrong" takes a PP-adjunct, "wrong about X". 
  * Again for the second how, we can paraphrase "about how it is that another dress compared" or "about the way how a dress compared", so again it's a free relative IMO (external function obl, internal function mark, which is suppressed in favor of the superordinate function in basic dependencies)
  * Nothing is non-projective in my analysis.

BTW in Slavic I think you could get proper correlative structures to break up the free relatives:

  * Zapytała o to, jak sukienka ma się do tej drugiej
  * (she) asked about it, how the dress compares to the other one ("it" <> "how" is the free relative transition split into both its functions)

**Comment by nschneid** [comment]
Hmm, obj(telling, wrong) is surprising to me, because "how wrong I was..." does not seem like an nominal—not telling *what* was wrong, but telling a degree of wrongness, or *that* something was wrong.

By contrast, with "how much it costs" or "how many there are" I could see that as an adjective coerced into a nominal (how much *money* etc.).

But I freely admit that I can never wrap my head around these fancy relative clause constructions.

Here's how inconsistent EWT is with these *how*-ADJ phrases: http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61bd1dd93eb4e&clustering=rel.label

**Comment by nschneid** [comment]
She informed me that I was wrong.
She informed me how I was wrong.
She informed me how wrong I was.
*She informed me my wrongness.

I think this shows "how wrong I was" is a clause, not an NP.

**Comment by amir-zeldes** [comment]
I think the proper ditransitive on Latinate verbs often feels bad, and "my wrongness" is just odd period IMO (compare "she told me my misdeeds"). But for me the main criterion here is the splittability which characterizes free relatives, i.e.:

  * She told me the the way how I was wrong (where "way" is the missing matrix noun which controls the relative, compare the Polish example above)

Basically most WH object situations can be interpreted this way, and I think it captures the difference between:

  * X verbs that CLAUSE (informed me that ABC happened, true ccomp)
  * X verbs WH-ARG-IN-CLAUSE (informed me what she ate, how it was, when it happened)

In the latter cases, the matrix object is focused on just the WH participant "I now know WHAT she ate", not "I now know THAT she ate", so the object clause fulfills the function of something [+edible]. In the "how wrong" examples, the thing I am being informed about is a degree of wrongness - if I pronominalize or interrogate it, that's ultimately what saturates the "thing informed about" argument.

**Comment by nschneid** [comment]
Oh interesting—you have "informed me what she ate"? To me that sounds odd; I would probably say "informed me **of** what she ate", but with "how" or "when" it sounds better. "She reminded me what she ate" sounds fine.

COCA search:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/985263/146657393-088ae6aa-0bbb-42ae-9dfb-1e3a375afd58.png">

So it definitely occurs. But "inform" seems to occur in this construction a lot less than "remind" (even considering the frequencies of these verbs):

|         without *of*               |          with *of*                   |
|---------------------------|---------------------------|
| inform* PRON what: 37     |  inform* PRON of what: 74 |
| inform* PRON how: 56      | inform* PRON of how: 25   |
| remind* PRON what: 554  | remind* PRON of what: 669 |
| remind* PRON how: 881   | remind* PRON of how: 791 |


- inform (bare verb): 12633
- remind (bare verb): 24141

**Comment by nschneid** [comment]
Anyway back to the original issue—I found some old documentation of free relative clauses: http://universaldependencies.org/docsv1/en/overview/specific-syntax.html#free-relatives

**Comment by nschneid** [comment]
Documented [here](https://universaldependencies.org/en/dep/fixed.html).
