### ISSUE TITLE
"#" as in "# 1" should be SYM, not NOUN

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#79]
https://github.com/UniversalDependencies/docs/issues/429

**Comment by nschneid** [comment]
cf. "$ 1", which should be nummod($/SYM, 1/NUM)

**Comment by nschneid** [comment]
See also https://github.com/UniversalDependencies/docs/issues/156

**Comment by amir-zeldes** [comment]
I know this corresponds to the PTB guidelines (nowithstanding versions of the Treebank where `$` is the tag for "$", instead of SYM), but I just wanted to point out that this is basically contrary to the general sentiment we've been seeing on the tracker, where most people would like to tag `-` meaning "to" as ADP, Internet abbreviations as whatever items they stand for/are pronounced as, etc. 

Maybe there is room to reconsider making some traditional cases of SYM be regular grammatical categories?

**Comment by nschneid** [comment]
https://github.com/UniversalDependencies/docs/issues/429 suggests as much, but under current guidelines it should be `SYM`.

**Comment by nschneid** [comment]
What about the Xpostag? Leave as `NN`? Here are the conventions for some of the other `SYM` types:

token | upos | xpos
------|------|-----
$    |   SYM  |   $
l    |   SYM   |  $
£   |    SYM |    $
%    |   SYM   |  NN
:(  |    SYM  |   NFP
:)   |   SYM   |  NFP
\+     |  SYM  |   SYM
\-   |    SYM   |  SYM
/    |   SYM   |  SYM
\>=  |    SYM   |  SYM
A  |     SYM  |   SYM
a   |    SYM   |  SYM
x    |   SYM  |   SYM

**Comment by amir-zeldes** [comment]
This is a real dilemma, because I hate revising established guidelines. It leads to tag set dialects and inconsistency. My gut feeling is that a minimum of things should be `SYM`, just like a minimum of things should have deprel `dep`, but I do acknowledge that existing LDC corpora use SYM this way. Maybe it's best to just live with it, but if I ever do stray from "choose a bad annotation scheme and stick to it", it would be for something like this :|

**Comment by nschneid** [comment]
The above commit changes the UPOS only. Leaving XPOS, morphology, dependencies alone. 

The distinction between `nummod(#, 123)` and other uses of "#" appears to be pretty consistent. E.g. "# 1)" in a list is headed by "1", whose XPOS is `LS`. (see UniversalDependencies/docs#156)
