### ISSUE TITLE
Foreign names analyzed as compound, should be flat

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#81]
- Sao Paulo
- Rio de Janeiro
- Porte de Vanves
- al - Qaeda
- El Paso
- El Paradero
- La Croce
- La Hacienda

etc.

**Comment by nschneid** [comment]
or we could introduce `flat:foreign`

**Comment by amir-zeldes** [comment]
I'd prefer foreignness to be in the Foreign feat, since otherwise you only see this for multiword foreign expressions (for example if someone says:

¡Ole!

In an English corpus, I'd like it to be Foreign=Yes, but it wouldn't have a flat relation of any kind. So I think these should be flat and foreign, but one is a deprel and the other is a foreign language identification (ideally coupled with what language it is, which we now have in GUM as well)

**Comment by amir-zeldes** [comment]
Sure, nothing stops people from using subtypes. I'm just not tempted to add these to any corpus I maintain and would probably steer new developers away from them if it were up to me, because we already have PROPN for names and Foreign for foreign, so this just adds a layer where we could have conflicting analyses (and it missed one word instances, as mentioned, so it's not really useful for retrieval). 

I think names are really an entity level property, and foreignness is a text-span property, but I'm happy enough with PROPN and Foreign as practical operationalizations, especially given that most UD corpora don't have NER or codeswitching/Lang annotations. Documenting the reason why something is flat seems beyond the scope of what deprels should be responsible for to me - stating that something is foreign or a name seems interesting, by contrast, but is additional information to the syntax tree itself.

**Comment by nschneid** [comment]
Per the new [foreign expressions policy](https://universaldependencies.org/foreign.html) I think we should just treat foreign names as flat and not specify a feature.

- [ ] [foreign articles/prepositions in non-flat structure](https://universal.grew.fr/?custom=6688c6509c945)
- [ ] [foreign words for Saint](https://universal.grew.fr/?custom=6688c5a003d33)
