### ISSUE TITLE
xpostag diff between LDC dataset

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/UD_English-EWT#85]
In the sentence below, token 4 originally in the LDC data has POS=`NN`. In the current MASTER branch this token has UPOSTAG=`NOUN` but what is the origin of the XPOSTAG=`VBG`?

```
# sent_id = weblog-blogspot.com_rigorousintuition_20060511134300_ENG_20060511_134300-0085
# text = It is the marrying off of young girls to older men often close relatives that enfurates me.
1       It      it      PRON    PRP     Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs  2       expl    2:expl  _
2       is      be      VERB    VBZ     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   0       root    0:root  _
3       the     the     DET     DT      Definite=Def|PronType=Art       4       det     4:det   _
4       marrying        marrying        NOUN    VBG     Number=Sing     2       nsubj   2:nsubj|16:nsubj        _
5       off     off     NOUN    NN      Number=Sing     4       advmod  4:advmod        _
6       of      of      ADP     IN      _       8       case    8:case  _
7       young   young   ADJ     JJ      Degree=Pos      8       amod    8:amod  _
8       girls   girl    NOUN    NNS     Number=Plur     4       nmod    4:nmod:of       _
9       to      to      ADP     IN      _       11      case    11:case _
10      older   older   ADJ     JJR     Degree=Cmp      11      amod    11:amod _
11      men     man     NOUN    NNS     Number=Plur     4       nmod    4:nmod:to       _
12      often   often   ADV     RB      _       14      advmod  14:advmod       _
13      close   close   ADJ     JJ      Degree=Pos      14      amod    14:amod _
14      relatives       relative        NOUN    NNS     Number=Plur     11      appos   11:appos        _
15      that    that    PRON    WDT     PronType=Rel    16      nsubj   4:ref   _
16      enfurates       enfurate        VERB    VBZ     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   4       acl:relcl       4:acl:relcl
     _
17      me      I       PRON    PRP     Case=Acc|Number=Sing|Person=1|PronType=Prs      16      obj     16:obj  SpaceAfter=No
18      .       .       PUNCT   .       _       2       punct   2:punct _
```

I am asking because the metadata value says that xpos are `manual native` so I am assuming this field was copied from LDC data and eventually manually fixed.

**Comment by manning** [comment]
Hi Alexandre, originally we decided to keep the stuff that LDC had done constant (sentence boundaries, tokenization, POS). That is true of the earlier UDv1 releases. 

But at some point, I'd have to check when, we decided that that was silly and have started deviating. We've restored original tokens rather than using LDC ASCII-ization and escaping. We've corrected parts of speech that we think are wrong. We haven't yet changed sentence boundaries, but there are some of them that are clearly wrong too, and we're intending to also start doing that. 😉

Specifically for XPOS: We have not systematically gone through all XPOS. But when we have noticed wrong XPOS, we have corrected them. We have done this by hand, normally when we are also correcting UPOS, but maybe also at other times if we've stared at a sentence. Our current policy is "defer to LDC unless wrong": That is, if it's sort of unclear what the right POS is, we leave it as LDC had it, but if it's clearly wrong then we fix it.

In the case at hand, this is a clear nominalized "marrying", as indicated by the "of" preceding "older men".

**Comment by manning** [comment]
p.s. It's not quite clear to me what to do with those metadata tags when the real situation is sort of mixed as described above....

**Comment by arademaker** [comment]
Yes, maybe we should allow a list of values in the metadata tags for such situations. Maybe @dan-zeman can suggest something. Anyway, I believe we can close this issue that I created only for double-check the differences I found during my work on https://github.com/System-T/UniversalPropositions.
