### ISSUE TITLE
"reason (that/why) CLAUSE": is this a relative clause?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#97]
As I noted in #96: 

Searching the corpus for "reason" I see `acl:relcl` is the typical analysis in examples such as "the main reason I wrote this post", "the primary reason we need these things", "the reason Senators Daschle and Leahy would have been targeted", "the only reason I would go to this particular QT", "the reason he transferred to the Alabama Air National Guard". But I wonder if it should be considered `acl` instead, because "reason" is not extracted from a core position of the embedded clause.

@amir-zeldes responded:

> I think "reason why" is not a relative, which properly should be "the reason due to which ...". For me "reason why" is an adnominal clause, but not relative.

**Comment by nschneid** [comment]
@dan-zeman @sebschu Do you agree this should be `acl`?

**Comment by amir-zeldes** [comment]
BTW, there is also the issue of parity with 'that' clauses, since you can say:

`They drowned for the reason that they didn't have life vests`

Which is maybe `acl` (I actually think it's adnominal `ccomp`, but I prob. won't win that fight), but not acl:relcl, as in:

`They drowned for the reason that I told you about`

I think if we use `acl` for the first example, then maybe we should use it for 'why' too, as well as for zero complementizer reason + clause: `the reason they drowned...`

**Comment by dan-zeman** [comment]
I agree it could be `acl` instead of `acl:relcl`. Note that if you remove `:relcl`, you should probably also rework the enhanced graph to make sure that the annotation stays consistent.

**Comment by nschneid** [comment]
It seems like somebody should investigate what other nouns this applies to—presumably [shell nouns](http://www.aclweb.org/anthology/D14-1056) like "problem", "issue", "concern", etc.

E.g. "there were concerns such action would lead to more chaos"

**Comment by nschneid** [comment]
Refer to relative clause guidelines: https://universaldependencies.org/en/dep/acl-relcl.html
